// RepVerify i18n — Quellsprache: Deutsch. Top-15-Sprachen, Englisch immer zuerst.
// Übersetzungsreihenfolge je Eintrag: en, zh, hi, es, fr, ar, bn, ru, pt, ur, id, ja, tr, ko
window.I18N_LANGS=[["en","English"],["zh","中文"],["hi","हिन्दी"],["es","Español"],["fr","Français"],["ar","العربية"],["bn","বাংলা"],["ru","Русский"],["pt","Português"],["ur","اردو"],["id","Bahasa Indonesia"],["de","Deutsch"],["ja","日本語"],["tr","Türkçe"],["ko","한국어"]];
window.I18N_ORDER=["en","zh","hi","es","fr","ar","bn","ru","pt","ur","id","ja","tr","ko"];
window.I18N_SRC={
"Einstellungen":["Settings","设置","सेटिंग्स","Ajustes","Réglages","الإعدادات","সেটিংস","Настройки","Definições","ترتیبات","Pengaturan","設定","Ayarlar","설정"],
"Konto":["Account","账户","खाता","Cuenta","Compte","الحساب","অ্যাকাউন্ট","Аккаунт","Conta","اکاؤنٹ","Akun","アカウント","Hesap","계정"],
"Benachrichtigungen":["Notifications","通知","सूचनाएं","Notificaciones","Notifications","الإشعارات","বিজ্ঞপ্তি","Уведомления","Notificações","اطلاعات","Notifikasi","通知","Bildirimler","알림"],
"Datenschutz":["Privacy","隐私","गोपनीयता","Privacidad","Confidentialité","الخصوصية","গোপনীয়তা","Приватность","Privacidade","رازداری","Privasi","プライバシー","Gizlilik","개인정보"],
"Feedback":["Feedback","反馈","प्रतिक्रिया","Comentarios","Retour","ملاحظات","মতামত","Обратная связь","Feedback","رائے","Masukan","フィードバック","Geri bildirim","피드백"],
"Profil":["Profile","个人资料","प्रोफ़ाइल","Perfil","Profil","الملف الشخصي","প্রোফাইল","Профиль","Perfil","پروفائل","Profil","プロフィール","Profil","프로필"],
"Anzeigename":["Display name","显示名称","प्रदर्शित नाम","Nombre visible","Nom affiché","الاسم المعروض","প্রদর্শিত নাম","Отображаемое имя","Nome de exibição","ظاہری نام","Nama tampilan","表示名","Görünen ad","표시 이름"],
"Speichern":["Save","保存","सहेजें","Guardar","Enregistrer","حفظ","সংরক্ষণ","Сохранить","Guardar","محفوظ کریں","Simpan","保存","Kaydet","저장"],
"Wird in Rankings angezeigt":["Shown in rankings","显示在排行榜中","रैंकिंग में दिखेगा","Se muestra en rankings","Affiché dans les classements","يظهر في التصنيفات","র‍্যাঙ্কিংয়ে দেখানো হয়","Отображается в рейтинге","Aparece nos rankings","درجہ بندی میں دکھایا جاتا ہے","Ditampilkan di peringkat","ランキングに表示","Sıralamalarda gösterilir","랭킹에 표시됨"],
"Limit erreicht":["Limit reached","已达上限","सीमा पूर्ण","Límite alcanzado","Limite atteinte","تم بلوغ الحد","সীমা পূর্ণ","Лимит исчерпан","Limite atingido","حد مکمل","Batas tercapai","上限に達しました","Sınıra ulaşıldı","한도 도달"],
"E-Mail":["Email","邮箱","ईमेल","Correo","E-mail","البريد الإلكتروني","ইমেল","Эл. почта","E-mail","ای میل","Email","メール","E-posta","이메일"],
"Region & Währung":["Region & currency","地区与货币","क्षेत्र और मुद्रा","Región y moneda","Région et devise","المنطقة والعملة","অঞ্চল ও মুদ্রা","Регион и валюта","Região e moeda","علاقہ اور کرنسی","Wilayah & mata uang","地域と通貨","Bölge ve para birimi","지역 및 통화"],
"Ändern":["Change","更改","बदलें","Cambiar","Modifier","تغيير","পরিবর্তন","Изменить","Alterar","تبدیل کریں","Ubah","変更","Değiştir","변경"],
"Sprache":["Language","语言","भाषा","Idioma","Langue","اللغة","ভাষা","Язык","Idioma","زبان","Bahasa","言語","Dil","언어"],
"Satzpause beim Aufnehmen":["Rest between sets while recording","录制时组间休息","रिकॉर्डिंग में सेट के बीच विराम","Descanso entre series al grabar","Pause entre séries à l'enregistrement","استراحة بين المجموعات أثناء التسجيل","রেকর্ডিংয়ে সেটের মাঝে বিরতি","Пауза между подходами при записи","Descanso entre séries ao gravar","ریکارڈنگ میں سیٹ کے درمیان وقفہ","Istirahat antar set saat merekam","記録中のセット間休憩","Kayıtta setler arası mola","녹화 중 세트 간 휴식"],
"Konto löschen":["Delete account","删除账户","खाता हटाएं","Eliminar cuenta","Supprimer le compte","حذف الحساب","অ্যাকাউন্ট মুছুন","Удалить аккаунт","Excluir conta","اکاؤنٹ حذف کریں","Hapus akun","アカウント削除","Hesabı sil","계정 삭제"],
"Halten zum Löschen":["Hold to delete","长按删除","हटाने के लिए दबाए रखें","Mantén para eliminar","Maintenir pour supprimer","اضغط مطولاً للحذف","মুছতে চেপে ধরুন","Удерживайте для удаления","Segure para excluir","حذف کے لیے دبائے رکھیں","Tahan untuk menghapus","長押しで削除","Silmek için basılı tut","길게 눌러 삭제"],
"Willst du nur pausieren statt löschen?":["Just want a break instead of deleting?","只想暂停而不是删除？","हटाने की बजाय बस रुकना चाहते हैं?","¿Solo quieres pausar en vez de eliminar?","Envie d'une pause plutôt que de supprimer ?","تريد استراحة بدلاً من الحذف؟","মুছে ফেলার বদলে বিরতি চান?","Хотите паузу вместо удаления?","Só quer pausar em vez de excluir?","حذف کے بجائے صرف وقفہ چاہتے ہیں؟","Hanya ingin jeda, bukan menghapus?","削除ではなく休止したい？","Silmek yerine ara mı vermek istiyorsun?","삭제 대신 잠시 쉬고 싶나요?"],
"Nur App entfernen (Konto bleibt bestehen)":["Remove app only (account stays)","仅移除应用（账户保留）","सिर्फ ऐप हटाएं (खाता रहेगा)","Quitar solo la app (la cuenta se conserva)","Retirer l'app seulement (compte conservé)","إزالة التطبيق فقط (يبقى الحساب)","শুধু অ্যাপ সরান (অ্যাকাউন্ট থাকবে)","Удалить только приложение (аккаунт останется)","Remover só o app (conta permanece)","صرف ایپ ہٹائیں (اکاؤنٹ رہے گا)","Hapus aplikasi saja (akun tetap)","アプリのみ削除（アカウントは残る）","Sadece uygulamayı kaldır (hesap kalır)","앱만 제거 (계정 유지)"],
"E-Mail-Benachrichtigungen":["Email notifications","邮件通知","ईमेल सूचनाएं","Notificaciones por correo","Notifications par e-mail","إشعارات البريد","ইমেল বিজ্ঞপ্তি","Email-уведомления","Notificações por e-mail","ای میل اطلاعات","Notifikasi email","メール通知","E-posta bildirimleri","이메일 알림"],
"Verifizierungsanfragen":["Verification requests","验证请求","सत्यापन अनुरोध","Solicitudes de verificación","Demandes de vérification","طلبات التحقق","যাচাই অনুরোধ","Запросы на проверку","Pedidos de verificação","تصدیق کی درخواستیں","Permintaan verifikasi","確認リクエスト","Doğrulama istekleri","검증 요청"],
"Wenn du als Prüfer ausgewählt wirst ·":["When you're picked as a reviewer ·","当你被选为审核员时 ·","जब आप समीक्षक चुने जाएं ·","Cuando te eligen como revisor ·","Quand tu es choisi comme vérificateur ·","عند اختيارك كمراجع ·","আপনি পরীক্ষক নির্বাচিত হলে ·","Когда вас выбрали проверяющим ·","Quando você é escolhido como revisor ·","جب آپ جائزہ کار منتخب ہوں ·","Saat kamu dipilih sebagai peninjau ·","審査員に選ばれたとき ·","İnceleyici seçildiğinde ·","검토자로 선택되면 ·"],
"Einheit bestätigt":["Unit confirmed","训练已确认","यूनिट पुष्ट","Unidad confirmada","Séance confirmée","تم تأكيد التمرين","ইউনিট নিশ্চিত","Тренировка подтверждена","Treino confirmado","یونٹ کی تصدیق","Unit dikonfirmasi","ユニット承認","Antrenman onaylandı","세션 승인됨"],
"Wenn deine Einheit alle Stimmen hat ·":["When your unit has all votes ·","当你的训练获得全部投票 ·","जब आपकी यूनिट को सभी वोट मिलें ·","Cuando tu unidad tiene todos los votos ·","Quand ta séance a tous les votes ·","عندما يكتمل تصويت تمرينك ·","আপনার ইউনিট সব ভোট পেলে ·","Когда собраны все голоса ·","Quando seu treino tem todos os votos ·","جب آپ کے یونٹ کو تمام ووٹ ملیں ·","Saat unitmu mendapat semua suara ·","全票が揃ったとき ·","Tüm oylar toplandığında ·","모든 투표가 완료되면 ·"],
"Ranking-Updates":["Ranking updates","排名更新","रैंकिंग अपडेट","Novedades del ranking","Mises à jour du classement","تحديثات التصنيف","র‍্যাঙ্কিং আপডেট","Обновления рейтинга","Atualizações do ranking","درجہ بندی اپڈیٹس","Pembaruan peringkat","ランキング更新","Sıralama güncellemeleri","랭킹 업데이트"],
"Tägliche Zusammenfassung ·":["Daily summary ·","每日摘要 ·","दैनिक सारांश ·","Resumen diario ·","Résumé quotidien ·","ملخص يومي ·","দৈনিক সারসংক্ষেপ ·","Ежедневная сводка ·","Resumo diário ·","روزانہ خلاصہ ·","Ringkasan harian ·","毎日のまとめ ·","Günlük özet ·","일일 요약 ·"],
"Monatliche Auszahlung":["Monthly payout","每月提现","मासिक भुगतान","Pago mensual","Versement mensuel","الدفعة الشهرية","মাসিক পেমেন্ট","Ежемесячная выплата","Pagamento mensal","ماہانہ ادائیگی","Pembayaran bulanan","毎月の支払い","Aylık ödeme","월간 지급"],
"Erinnerung vor Monatsende ·":["Reminder before month's end ·","月底前提醒 ·","महीने के अंत से पहले याद ·","Recordatorio antes de fin de mes ·","Rappel avant la fin du mois ·","تذكير قبل نهاية الشهر ·","মাস শেষের আগে অনুস্মারক ·","Напоминание в конце месяца ·","Lembrete antes do fim do mês ·","مہینے کے آخر سے پہلے یاد دہانی ·","Pengingat sebelum akhir bulan ·","月末前のリマインド ·","Ay sonundan önce hatırlatma ·","월말 전 알림 ·"],
"Sichtbarkeit":["Visibility","可见性","दृश्यता","Visibilidad","Visibilité","الظهور","দৃশ্যমানতা","Видимость","Visibilidade","نمائش","Visibilitas","公開設定","Görünürlük","공개 설정"],
"Aktuell: Name in Rankings":["Currently: name in rankings","当前：排行榜中的名字","वर्तमान: रैंकिंग में नाम","Actual: nombre en rankings","Actuel : nom dans les classements","حالياً: الاسم في التصنيفات","বর্তমান: র‍্যাঙ্কিংয়ে নাম","Сейчас: имя в рейтинге","Atual: nome nos rankings","فی الحال: درجہ بندی میں نام","Saat ini: nama di peringkat","現在：ランキングの名前","Şu an: sıralamadaki isim","현재: 랭킹의 이름"],
"Aktuell: Punkte bei Statistiken":["Currently: points in statistics","当前：统计中的分数","वर्तमान: आंकड़ों में अंक","Actual: puntos en estadísticas","Actuel : points dans les statistiques","حالياً: النقاط في الإحصائيات","বর্তমান: পরিসংখ্যানে পয়েন্ট","Сейчас: очки в статистике","Atual: pontos nas estatísticas","فی الحال: اعدادوشمار میں پوائنٹس","Saat ini: poin di statistik","現在：統計のポイント","Şu an: istatistiklerdeki puanlar","현재: 통계의 포인트"],
"Statistiken":["Statistics","统计","आंकड़े","Estadísticas","Statistiques","الإحصائيات","পরিসংখ্যান","Статистика","Estatísticas","اعدادوشمار","Statistik","統計","İstatistikler","통계"],
"unscharf":["blurred","模糊","धुंधला","difuminado","flouté","ضبابي","ঝাপসা","размыто","desfocado","دھندلا","buram","ぼかし","bulanık","흐림"],
"scharf":["sharp","清晰","स्पष्ट","nítido","net","واضح","স্পষ্ট","чётко","nítido","واضح","jelas","くっきり","net","선명"],
"Videos werden automatisch gelöscht":["Videos are deleted automatically","视频会自动删除","वीडियो अपने आप हट जाते हैं","Los vídeos se eliminan automáticamente","Les vidéos sont supprimées automatiquement","تُحذف الفيديوهات تلقائياً","ভিডিও স্বয়ংক্রিয়ভাবে মুছে যায়","Видео удаляются автоматически","Os vídeos são excluídos automaticamente","ویڈیوز خودکار حذف ہو جاتی ہیں","Video dihapus otomatis","動画は自動的に削除されます","Videolar otomatik silinir","영상은 자동 삭제됩니다"],
", sobald die Prüfung abgeschlossen ist und keine Beschwerde vorliegt (24 h Beschwerdefenster). Videos können nicht behalten werden — der Zugriff der Prüfer endet mit ihrer Entscheidung.":[", once the review is complete and no complaint is filed (24 h complaint window). Videos cannot be kept — reviewer access ends with their decision.","，审核完成且无投诉后（24小时投诉期）。视频无法保留——审核员的访问权限随其决定结束。","，समीक्षा पूरी होने और कोई शिकायत न होने पर (24 घंटे की शिकायत अवधि)। वीडियो रखे नहीं जा सकते — समीक्षक की पहुंच उनके निर्णय के साथ समाप्त होती है।",", en cuanto la revisión termina y no hay queja (ventana de 24 h). Los vídeos no se pueden conservar: el acceso del revisor termina con su decisión.",", dès que la vérification est terminée et sans plainte (fenêtre de 24 h). Les vidéos ne peuvent pas être conservées — l'accès du vérificateur prend fin avec sa décision.","، بمجرد اكتمال المراجعة وعدم وجود شكوى (نافذة 24 ساعة). لا يمكن الاحتفاظ بالفيديوهات — ينتهي وصول المراجع بقراره.",", পর্যালোচনা শেষ হলে এবং কোনো অভিযোগ না থাকলে (২৪ ঘণ্টার অভিযোগ সময়)। ভিডিও রাখা যায় না — সিদ্ধান্তের সাথে পরীক্ষকের প্রবেশাধিকার শেষ হয়।",", как только проверка завершена и нет жалобы (окно 24 ч). Видео нельзя сохранить — доступ проверяющих заканчивается с их решением.",", assim que a revisão termina e não há reclamação (janela de 24 h). Os vídeos não podem ser mantidos — o acesso do revisor termina com sua decisão.","، جیسے ہی جائزہ مکمل ہو اور کوئی شکایت نہ ہو (24 گھنٹے کی مدت)۔ ویڈیوز رکھی نہیں جا سکتیں — جائزہ کار کی رسائی فیصلے کے ساتھ ختم ہو جاتی ہے۔",", setelah peninjauan selesai dan tidak ada keluhan (jendela 24 jam). Video tidak dapat disimpan — akses peninjau berakhir dengan keputusannya.","。審査完了かつ異議申し立てがない場合（24時間の異議期間）。動画は保持できません — 審査員のアクセスは判定と同時に終了します。",", inceleme tamamlanınca ve şikâyet yoksa (24 saatlik itiraz süresi). Videolar saklanamaz — inceleyicinin erişimi kararıyla sona erer.",", 검토가 완료되고 이의가 없으면 (24시간 이의 기간). 영상은 보관할 수 없으며 검토자의 접근은 판정과 함께 종료됩니다."],
"Hilf uns zu verbessern":["Help us improve","帮助我们改进","हमें बेहतर बनाने में मदद करें","Ayúdanos a mejorar","Aide-nous à nous améliorer","ساعدنا على التحسّن","আমাদের উন্নত করতে সাহায্য করুন","Помогите нам стать лучше","Ajude-nos a melhorar","بہتری میں ہماری مدد کریں","Bantu kami berkembang","改善にご協力ください","Gelişmemize yardım et","개선을 도와주세요"],
"App bewerten":["Rate the app","评价应用","ऐप रेट करें","Valorar la app","Noter l'app","قيّم التطبيق","অ্যাপ রেট করুন","Оценить приложение","Avaliar o app","ایپ کی درجہ بندی کریں","Beri nilai aplikasi","アプリを評価","Uygulamayı değerlendir","앱 평가하기"],
"Öffnet die Store-Seite":["Opens the store page","打开商店页面","स्टोर पेज खोलता है","Abre la página de la tienda","Ouvre la page du store","يفتح صفحة المتجر","স্টোর পৃষ্ঠা খোলে","Откроет страницу магазина","Abre a página da loja","اسٹور صفحہ کھولتا ہے","Membuka halaman toko","ストアページを開く","Mağaza sayfasını açar","스토어 페이지 열기"],
"Fehler melden":["Report a bug","报告问题","समस्या बताएं","Informar de un error","Signaler un bug","الإبلاغ عن خطأ","সমস্যা জানান","Сообщить об ошибке","Reportar erro","خرابی کی اطلاع دیں","Laporkan bug","不具合を報告","Hata bildir","오류 신고"],
"Problem mit einer Funktion":["Problem with a feature","功能出现问题","किसी फीचर में समस्या","Problema con una función","Problème avec une fonction","مشكلة في ميزة","কোনো ফিচারে সমস্যা","Проблема с функцией","Problema com uma função","کسی فیچر میں مسئلہ","Masalah dengan fitur","機能の問題","Bir özellikte sorun","기능 문제"],
"Idee einreichen":["Submit an idea","提交想法","सुझाव भेजें","Enviar una idea","Proposer une idée","إرسال فكرة","আইডিয়া পাঠান","Предложить идею","Enviar ideia","خیال بھیجیں","Kirim ide","アイデアを送る","Fikir gönder","아이디어 제출"],
"Feature-Wunsch oder Verbesserung":["Feature request or improvement","功能需求或改进","फीचर अनुरोध या सुधार","Petición de función o mejora","Demande de fonctionnalité ou amélioration","طلب ميزة أو تحسين","ফিচার অনুরোধ বা উন্নতি","Запрос функции или улучшение","Pedido de recurso ou melhoria","فیچر کی درخواست یا بہتری","Permintaan fitur atau perbaikan","機能要望や改善案","Özellik isteği veya iyileştirme","기능 요청 또는 개선"],
"Nutzungsbedingungen":["Terms of use","使用条款","उपयोग की शर्तें","Términos de uso","Conditions d'utilisation","شروط الاستخدام","ব্যবহারের শর্তাবলী","Условия использования","Termos de uso","استعمال کی شرائط","Ketentuan penggunaan","利用規約","Kullanım koşulları","이용약관"],
"Dashboard":["Dashboard","主页","डैशबोर्ड","Panel","Tableau de bord","اللوحة الرئيسية","ড্যাশবোর্ড","Дашборд","Painel","ڈیش بورڈ","Dasbor","ダッシュボード","Panel","대시보드"],
"Programm":["Program","计划","प्रोग्राम","Programa","Programme","البرنامج","প্রোগ্রাম","Программа","Programa","پروگرام","Program","プログラム","Program","프로그램"],
"Monats-Erstattung möglich":["Monthly refund possible","可获每月返还","मासिक रिफंड संभव","Reembolso mensual posible","Remboursement mensuel possible","استرداد شهري ممكن","মাসিক ফেরত সম্ভব","Возможен месячный возврат","Reembolso mensal possível","ماہانہ واپسی ممکن","Pengembalian bulanan dimungkinkan","月次返金が可能","Aylık iade mümkün","월간 환급 가능"],
"Monatsfortschritt":["Monthly progress","本月进度","मासिक प्रगति","Progreso mensual","Progression du mois","التقدم الشهري","মাসিক অগ্রগতি","Прогресс за месяц","Progresso mensal","ماہانہ پیش رفت","Kemajuan bulanan","今月の進捗","Aylık ilerleme","월간 진행"],
"Einheiten":["Units","训练","यूनिट","Unidades","Séances","تمارين","ইউনিট","Тренировки","Treinos","یونٹس","Unit","ユニット","Antrenmanlar","세션"],
"Details":["Details","详情","विवरण","Detalles","Détails","التفاصيل","বিস্তারিত","Подробнее","Detalhes","تفصیلات","Detail","詳細","Detaylar","상세"],
"Abgeschlossen":["Completed","已完成","पूर्ण","Completadas","Terminées","مكتمل","সম্পন্ন","Завершено","Concluídos","مکمل","Selesai","完了","Tamamlanan","완료"],
"Heute":["Today","今天","आज","Hoy","Aujourd'hui","اليوم","আজ","Сегодня","Hoje","آج","Hari ini","今日","Bugün","오늘"],
"Einheit offen":["Unit open","训练待完成","यूनिट बाकी","Unidad pendiente","Séance à faire","التمرين متاح","ইউনিট বাকি","Тренировка не сделана","Treino pendente","یونٹ باقی","Unit belum","未実施","Antrenman bekliyor","세션 대기"],
"Ranking":["Ranking","排名","रैंकिंग","Ranking","Classement","التصنيف","র‍্যাঙ্কিং","Рейтинг","Ranking","درجہ بندی","Peringkat","ランキング","Sıralama","랭킹"],
"Guthaben":["Balance","余额","बैलेंस","Saldo","Solde","الرصيد","ব্যালেন্স","Баланс","Saldo","بیلنس","Saldo","残高","Bakiye","잔액"],
"verfügbar":["available","可用","उपलब्ध","disponible","disponible","متاح","উপলব্ধ","доступно","disponível","دستیاب","tersedia","利用可能","kullanılabilir","사용 가능"],
"Heutige Einheit":["Today's unit","今日训练","आज की यूनिट","Unidad de hoy","Séance du jour","تمرين اليوم","আজকের ইউনিট","Тренировка на сегодня","Treino de hoje","آج کا یونٹ","Unit hari ini","今日のユニット","Bugünkü antrenman","오늘의 세션"],
"Meist genutzte Übungen":["Most used exercises","最常用动作","सबसे ज्यादा किए व्यायाम","Ejercicios más usados","Exercices les plus utilisés","التمارين الأكثر استخداماً","সবচেয়ে বেশি ব্যবহৃত ব্যায়াম","Частые упражнения","Exercícios mais usados","سب سے زیادہ استعمال شدہ مشقیں","Latihan paling sering","よく使う種目","En çok kullanılan hareketler","자주 한 운동"],
"Durchmischen bringt Extra-Ranking-Punkte":["Mixing it up earns extra ranking points","多样化训练可获额外排名分","विविधता से अतिरिक्त रैंकिंग अंक","Variar da puntos extra de ranking","Varier rapporte des points de classement bonus","التنويع يمنح نقاط تصنيف إضافية","বৈচিত্র্যে অতিরিক্ত র‍্যাঙ্কিং পয়েন্ট","Разнообразие даёт бонусные очки","Variar rende pontos extras de ranking","تنوع سے اضافی درجہ بندی پوائنٹس","Variasi memberi poin peringkat ekstra","種目を混ぜるとボーナスポイント","Çeşitlilik ekstra sıralama puanı kazandırır","다양하게 하면 추가 랭킹 포인트"],
"Trainingsprogramm":["Training program","训练计划","ट्रेनिंग प्रोग्राम","Programa de entrenamiento","Programme d'entraînement","برنامج التدريب","প্রশিক্ষণ প্রোগ্রাম","Программа тренировок","Programa de treino","تربیتی پروگرام","Program latihan","トレーニングプログラム","Antrenman programı","트레이닝 프로그램"],
"Übersicht":["Overview","概览","अवलोकन","Resumen","Aperçu","نظرة عامة","সারসংক্ষেপ","Обзор","Visão geral","جائزہ","Ringkasan","概要","Genel bakış","개요"],
"Anfänger":["Beginner","初级","शुरुआती","Principiante","Débutant","مبتدئ","শিক্ষানবিস","Новичок","Iniciante","ابتدائی","Pemula","初級","Başlangıç","초급"],
"Mittelstufe":["Intermediate","中级","मध्यम","Intermedio","Intermédiaire","متوسط","মধ্যবর্তী","Средний","Intermediário","درمیانہ","Menengah","中級","Orta seviye","중급"],
"Fortgeschritten":["Advanced","高级","उन्नत","Avanzado","Avancé","متقدم","উন্নত","Продвинутый","Avançado","اعلیٰ","Lanjutan","上級","İleri seviye","고급"],
"Profi":["Pro","专业","प्रो","Pro","Pro","محترف","প্রো","Профи","Pro","پرو","Pro","プロ","Profesyonel","프로"],
"Freigeschaltet":["Unlocked","已解锁","अनलॉक","Desbloqueado","Débloqué","مفتوح","আনলকড","Открыто","Desbloqueado","کھلا","Terbuka","解放済み","Açık","해제됨"],
"Aktiv":["Active","当前","सक्रिय","Activo","Actif","نشط","সক্রিয়","Активно","Ativo","فعال","Aktif","アクティブ","Aktif","활성"],
"Gemeistert":["Mastered","已精通","महारत","Dominado","Maîtrisé","متقَن","আয়ত্ত","Освоено","Dominado","مہارت حاصل","Dikuasai","マスター済み","Ustalaşıldı","마스터"],
"Gesperrt":["Locked","已锁定","लॉक","Bloqueado","Verrouillé","مقفل","লকড","Заблокировано","Bloqueado","مقفل","Terkunci","ロック中","Kilitli","잠김"],
"Noch gesperrt":["Still locked","尚未解锁","अभी लॉक","Aún bloqueado","Encore verrouillé","لا يزال مقفلاً","এখনও লকড","Пока заблокировано","Ainda bloqueado","ابھی مقفل","Masih terkunci","まだロック中","Henüz kilitli","아직 잠김"],
"Kommt bald":["Coming soon","即将推出","जल्द आ रहा","Próximamente","Bientôt disponible","قريباً","শীঘ্রই আসছে","Скоро","Em breve","جلد آرہا ہے","Segera hadir","近日公開","Yakında","곧 출시"],
"Kommt bald.":["Coming soon.","即将推出。","जल्द आ रहा है।","Próximamente.","Bientôt disponible.","قريباً.","শীঘ্রই আসছে।","Скоро.","Em breve.","جلد آرہا ہے۔","Segera hadir.","近日公開。","Yakında.","곧 출시됩니다."],
"Übungen":["Exercises","动作","व्यायाम","Ejercicios","Exercices","تمارين","ব্যায়াম","Упражнения","Exercícios","مشقیں","Latihan","種目","Hareketler","운동"],
"Tagesziel erreicht":["Daily goal reached","已达每日目标","दैनिक लक्ष्य पूरा","Meta diaria lograda","Objectif du jour atteint","تحقق هدف اليوم","দৈনিক লক্ষ্য অর্জিত","Дневная цель достигнута","Meta diária atingida","روزانہ ہدف مکمل","Target harian tercapai","1日の目標達成","Günlük hedefe ulaşıldı","일일 목표 달성"],
"Schließen":["Close","关闭","बंद करें","Cerrar","Fermer","إغلاق","বন্ধ","Закрыть","Fechar","بند کریں","Tutup","閉じる","Kapat","닫기"],
"Einheit aufnehmen":["Record unit","录制训练","यूनिट रिकॉर्ड करें","Grabar unidad","Enregistrer la séance","تسجيل التمرين","ইউনিট রেকর্ড করুন","Записать тренировку","Gravar treino","یونٹ ریکارڈ کریں","Rekam unit","ユニットを記録","Antrenmanı kaydet","세션 녹화"],
"Einheit:":["Unit:","训练：","यूनिट:","Unidad:","Séance :","التمرين:","ইউনিট:","Тренировка:","Treino:","یونٹ:","Unit:","ユニット：","Antrenman:","세션:"],
"Pkt · Vielfalt:":["pts · variety:","分 · 多样性：","अंक · विविधता:","pts · variedad:","pts · variété :","نقطة · التنويع:","পয়েন্ট · বৈচিত্র্য:","очк. · разнообразие:","pts · variedade:","پوائنٹس · تنوع:","poin · variasi:","pt・バリエーション：","puan · çeşitlilik:","점 · 다양성:"],
"Übungen · Ranking-Wert:":["exercises · ranking value:","个动作 · 排名值：","व्यायाम · रैंकिंग मान:","ejercicios · valor de ranking:","exercices · valeur de classement :","تمارين · قيمة التصنيف:","ব্যায়াম · র‍্যাঙ্কিং মান:","упражн. · очки рейтинга:","exercícios · valor de ranking:","مشقیں · درجہ بندی قدر:","latihan · nilai peringkat:","種目・ランキング値：","hareket · sıralama değeri:","운동 · 랭킹 값:"],
"Verify-Warteschlange":["Verify queue","审核队列","सत्यापन कतार","Cola de verificación","File de vérification","قائمة التحقق","যাচাই সারি","Очередь проверки","Fila de verificação","تصدیق کی قطار","Antrean verifikasi","確認キュー","Doğrulama kuyruğu","검증 대기열"],
"Deine Verify-Bilanz":["Your verify record","你的审核记录","आपका सत्यापन रिकॉर्ड","Tu historial de verificación","Ton bilan de vérification","سجل التحقق الخاص بك","আপনার যাচাই রেকর্ড","Ваша статистика проверок","Seu histórico de verificação","آپ کا تصدیقی ریکارڈ","Rekam verifikasimu","あなたの確認実績","Doğrulama geçmişin","나의 검증 기록"],
"Verifiziert":["Verified","已审核","सत्यापित","Verificadas","Vérifiées","تم التحقق","যাচাইকৃত","Проверено","Verificados","تصدیق شدہ","Terverifikasi","確認済み","Doğrulanan","검증 완료"],
"diesen Monat":["this month","本月","इस महीने","este mes","ce mois-ci","هذا الشهر","এই মাসে","в этом месяце","este mês","اس مہینے","bulan ini","今月","bu ay","이번 달"],
"Offen":["Open","待处理","लंबित","Pendientes","En attente","معلق","মুলতুবি","Открыто","Pendentes","زیر التوا","Terbuka","未処理","Bekleyen","대기 중"],
"Anfragen":["requests","个请求","अनुरोध","solicitudes","demandes","طلبات","অনুরোধ","запросов","pedidos","درخواستیں","permintaan","件のリクエスト","istek","요청"],
"Penaltys":["Penalties","处罚","पेनल्टी","Penalizaciones","Pénalités","عقوبات","পেনাল্টি","Штрафы","Penalidades","پنالٹیز","Penalti","ペナルティ","Cezalar","페널티"],
"alles sauber":["all clean","一切正常","सब ठीक","todo limpio","tout est propre","كل شيء نظيف","সব ঠিক আছে","всё чисто","tudo limpo","سب ٹھیک","semua bersih","問題なし","her şey temiz","이상 없음"],
"bei 3 wird das Konto blockiert":["at 3 the account gets blocked","满3次账户将被封锁","3 पर खाता ब्लॉक होगा","con 3 se bloquea la cuenta","à 3, le compte est bloqué","عند 3 يتم حظر الحساب","৩ হলে অ্যাকাউন্ট ব্লক হবে","при 3 аккаунт блокируется","com 3 a conta é bloqueada","3 پر اکاؤنٹ بلاک ہو جائے گا","pada 3 akun diblokir","3回でアカウント停止","3 olunca hesap engellenir","3회면 계정이 차단됩니다"],
"Falsche Bestätigungen führen zu Konto-Einschränkungen. Dein Videozugriff endet mit deiner Entscheidung.":["False confirmations lead to account restrictions. Your video access ends with your decision.","虚假确认将导致账户受限。你的视频访问权限随你的决定结束。","गलत पुष्टि से खाते पर प्रतिबंध लगते हैं। आपकी वीडियो पहुंच आपके निर्णय के साथ समाप्त होती है।","Las confirmaciones falsas conllevan restricciones de cuenta. Tu acceso al vídeo termina con tu decisión.","Les fausses confirmations entraînent des restrictions de compte. Ton accès à la vidéo prend fin avec ta décision.","التأكيدات الخاطئة تؤدي إلى قيود على الحساب. ينتهي وصولك للفيديو بقرارك.","ভুল নিশ্চিতকরণে অ্যাকাউন্টে বিধিনিষেধ আসে। সিদ্ধান্তের সাথে আপনার ভিডিও প্রবেশাধিকার শেষ হয়।","Ложные подтверждения ведут к ограничениям аккаунта. Доступ к видео заканчивается с вашим решением.","Confirmações falsas levam a restrições de conta. Seu acesso ao vídeo termina com sua decisão.","غلط تصدیقات اکاؤنٹ پر پابندیوں کا باعث بنتی ہیں۔ آپ کی ویڈیو رسائی فیصلے کے ساتھ ختم ہو جاتی ہے۔","Konfirmasi palsu menyebabkan pembatasan akun. Akses videomu berakhir dengan keputusanmu.","虚偽の承認はアカウント制限につながります。動画へのアクセスは判定と同時に終了します。","Yanlış onaylar hesap kısıtlamalarına yol açar. Video erişimin kararınla sona erer.","허위 승인은 계정 제한으로 이어집니다. 영상 접근은 판정과 함께 종료됩니다."],
"Rankings":["Rankings","排行榜","रैंकिंग","Rankings","Classements","التصنيفات","র‍্যাঙ্কিং","Рейтинги","Rankings","درجہ بندیاں","Peringkat","ランキング","Sıralamalar","랭킹"],
"Preispool":["Prize pool","奖池","इनाम पूल","Bote de premios","Cagnotte","مجموع الجوائز","পুরস্কার তহবিল","Призовой фонд","Prêmio acumulado","انعامی پول","Kumpulan hadiah","賞金プール","Ödül havuzu","상금 풀"],
"Aus nicht abgerufenen Erstattungen":["From unclaimed refunds","来自未领取的返还","बिना लिए गए रिफंड से","De reembolsos no reclamados","Issu des remboursements non réclamés","من المبالغ المستردة غير المطالب بها","দাবি না করা ফেরত থেকে","Из невостребованных возвратов","De reembolsos não resgatados","غیر وصول شدہ واپسیوں سے","Dari pengembalian yang tak diklaim","未受領の返金から","Talep edilmeyen iadelerden","미수령 환급금에서"],
"+0,25 € pro gewonnene Ranking-Position · Auszahlung Monatsende":["+0.25 per ranking position gained · paid at month's end","每上升一名 +0.25 · 月底支付","हर रैंक बढ़ने पर +0.25 · माह के अंत में भुगतान","+0,25 por puesto ganado · pago a fin de mes","+0,25 par place gagnée · versé en fin de mois","‏+0.25 لكل مركز مكتسب · يُدفع نهاية الشهر","প্রতি অর্জিত র‍্যাঙ্কে +০.২৫ · মাস শেষে পরিশোধ","+0,25 за каждую позицию · выплата в конце месяца","+0,25 por posição ganha · pago no fim do mês","ہر حاصل شدہ پوزیشن پر ‎+0.25 · مہینے کے آخر میں ادائیگی","+0,25 per posisi naik · dibayar akhir bulan","順位1つ上昇ごとに+0.25・月末に支払い","Kazanılan her sıra için +0,25 · ay sonunda ödenir","순위 상승당 +0.25 · 월말 지급"],
"Ranking basiert auf Einheiten-Punkten + Vielfalts-Bonus":["Ranking is based on unit points + variety bonus","排名基于训练分数+多样性奖励","रैंकिंग यूनिट अंक + विविधता बोनस पर आधारित","El ranking se basa en puntos + bono de variedad","Le classement repose sur les points + bonus de variété","يعتمد التصنيف على نقاط التمارين + مكافأة التنويع","র‍্যাঙ্কিং ইউনিট পয়েন্ট + বৈচিত্র্য বোনাসে ভিত্তি","Рейтинг основан на очках + бонус за разнообразие","Ranking baseado em pontos + bônus de variedade","درجہ بندی یونٹ پوائنٹس + تنوع بونس پر مبنی","Peringkat berdasarkan poin unit + bonus variasi","ランキングはポイント+バリエーションボーナスで決定","Sıralama puan + çeşitlilik bonusuna dayanır","랭킹은 포인트 + 다양성 보너스 기준"],
"Rewards":["Rewards","奖励","रिवॉर्ड","Recompensas","Récompenses","المكافآت","রিওয়ার্ড","Награды","Recompensas","انعامات","Hadiah","リワード","Ödüller","리워드"]
};
Object.assign(window.I18N_SRC,{
"Training. Verifiziert. Belohnt.":["Train. Verified. Rewarded.","训练。验证。奖励。","ट्रेनिंग। सत्यापित। पुरस्कृत।","Entrena. Verificado. Recompensado.","Entraînement. Vérifié. Récompensé.","تدرّب. موثّق. مكافأ.","প্রশিক্ষণ। যাচাইকৃত। পুরস্কৃত।","Тренируйся. Проверено. Вознаграждено.","Treine. Verificado. Recompensado.","تربیت۔ تصدیق شدہ۔ انعام یافتہ۔","Latihan. Terverifikasi. Dihargai.","トレーニング。検証。報酬。","Antrenman. Doğrulandı. Ödüllendirildi.","훈련. 검증. 보상."],
"Mit Google anmelden":["Sign in with Google","使用 Google 登录","Google से साइन इन करें","Iniciar sesión con Google","Se connecter avec Google","تسجيل الدخول عبر Google","Google দিয়ে সাইন ইন","Войти через Google","Entrar com Google","Google سے سائن ان کریں","Masuk dengan Google","Googleでログイン","Google ile giriş yap","Google로 로그인"],
"oder":["or","或","या","o","ou","أو","অথবা","или","ou","یا","atau","または","veya","또는"],
"Magic-Link senden":["Send magic link","发送魔法链接","मैजिक लिंक भेजें","Enviar enlace mágico","Envoyer le lien magique","إرسال رابط الدخول","ম্যাজিক লিঙ্ক পাঠান","Отправить магическую ссылку","Enviar link mágico","میجک لنک بھیجیں","Kirim tautan ajaib","マジックリンクを送信","Sihirli bağlantı gönder","매직 링크 보내기"],
"Konto blockiert":["Account blocked","账户已封锁","खाता ब्लॉक","Cuenta bloqueada","Compte bloqué","الحساب محظور","অ্যাকাউন্ট ব্লকড","Аккаунт заблокирован","Conta bloqueada","اکاؤنٹ بلاک","Akun diblokir","アカウント停止","Hesap engellendi","계정 차단됨"],
"Du hast 3 Penaltys erreicht. Dein Konto wurde gesperrt und wird vom Admin geprüft. Bei Fragen: Feedback → Fehler melden.":["You reached 3 penalties. Your account is locked and under admin review. Questions: Feedback → Report a bug.","你已累计3次处罚。账户已被锁定，等待管理员审核。如有疑问：反馈 → 报告问题。","आपको 3 पेनल्टी मिलीं। खाता लॉक है और एडमिन जांच रहा है। प्रश्न: प्रतिक्रिया → समस्या बताएं।","Has llegado a 3 penalizaciones. Tu cuenta está bloqueada y el admin la revisa. Dudas: Comentarios → Informar de un error.","Tu as atteint 3 pénalités. Ton compte est bloqué et vérifié par l'admin. Questions : Retour → Signaler un bug.","وصلت إلى 3 عقوبات. حسابك محظور وقيد مراجعة المشرف. للاستفسار: ملاحظات ← الإبلاغ عن خطأ.","আপনি ৩টি পেনাল্টি পেয়েছেন। অ্যাকাউন্ট লকড এবং অ্যাডমিন পর্যালোচনা করছে। প্রশ্ন: মতামত → সমস্যা জানান।","У вас 3 штрафа. Аккаунт заблокирован и проверяется админом. Вопросы: Обратная связь → Сообщить об ошибке.","Você atingiu 3 penalidades. Sua conta está bloqueada e em análise pelo admin. Dúvidas: Feedback → Reportar erro.","آپ کو 3 پنالٹیز ملیں۔ اکاؤنٹ مقفل ہے اور ایڈمن جائزہ لے رہا ہے۔ سوالات: رائے ← خرابی کی اطلاع دیں۔","Kamu mencapai 3 penalti. Akunmu terkunci dan sedang ditinjau admin. Pertanyaan: Masukan → Laporkan bug.","ペナルティが3回に達しました。アカウントは停止され、管理者が確認中です。質問はフィードバック→不具合を報告へ。","3 cezaya ulaştın. Hesabın kilitlendi ve yönetici inceliyor. Sorular: Geri bildirim → Hata bildir.","페널티 3회에 도달했습니다. 계정이 잠겼으며 관리자가 검토 중입니다. 문의: 피드백 → 오류 신고."],
"Abmelden":["Sign out","退出登录","साइन आउट","Cerrar sesión","Se déconnecter","تسجيل الخروج","সাইন আউট","Выйти","Sair","سائن آؤٹ","Keluar","ログアウト","Çıkış yap","로그아웃"],
"Wähle deine Region":["Choose your region","选择你的地区","अपना क्षेत्र चुनें","Elige tu región","Choisis ta région","اختر منطقتك","আপনার অঞ্চল বাছুন","Выберите регион","Escolha sua região","اپنا علاقہ منتخب کریں","Pilih wilayahmu","地域を選択","Bölgeni seç","지역 선택"],
"Preise, Erstattungen und Auszahlungen richten sich nach deiner Region.":["Prices, refunds and payouts depend on your region.","价格、返还和提现取决于你的地区。","कीमतें, रिफंड और भुगतान आपके क्षेत्र पर निर्भर हैं।","Precios, reembolsos y pagos dependen de tu región.","Les prix, remboursements et versements dépendent de ta région.","تعتمد الأسعار والمبالغ المستردة والمدفوعات على منطقتك.","মূল্য, ফেরত ও পেমেন্ট আপনার অঞ্চলের উপর নির্ভর করে।","Цены, возвраты и выплаты зависят от вашего региона.","Preços, reembolsos e pagamentos dependem da sua região.","قیمتیں، واپسیاں اور ادائیگیاں آپ کے علاقے پر منحصر ہیں۔","Harga, pengembalian, dan pembayaran tergantung wilayahmu.","価格・返金・支払いは地域によって異なります。","Fiyatlar, iadeler ve ödemeler bölgene bağlıdır.","가격, 환급, 지급은 지역에 따라 다릅니다."],
"Automatisch erkennen":["Detect automatically","自动检测","स्वतः पहचानें","Detectar automáticamente","Détection automatique","اكتشاف تلقائي","স্বয়ংক্রিয় শনাক্ত","Определить автоматически","Detectar automaticamente","خودکار شناخت","Deteksi otomatis","自動検出","Otomatik algıla","자동 감지"],
"Suchen…":["Search…","搜索…","खोजें…","Buscar…","Rechercher…","بحث…","খুঁজুন…","Поиск…","Pesquisar…","تلاش کریں…","Cari…","検索…","Ara…","검색…"],
"Abbruch":["Cancel","取消","रद्द","Cancelar","Annuler","إلغاء","বাতিল","Отмена","Cancelar","منسوخ","Batal","中止","İptal","취소"],
"Abbrechen":["Cancel","取消","रद्द करें","Cancelar","Annuler","إلغاء","বাতিল করুন","Отмена","Cancelar","منسوخ کریں","Batal","キャンセル","İptal","취소"],
"Einheit bestätigen":["Confirm unit","确认训练","यूनिट पुष्ट करें","Confirmar unidad","Valider la séance","تأكيد التمرين","ইউনিট নিশ্চিত করুন","Подтвердить тренировку","Confirmar treino","یونٹ کی تصدیق کریں","Konfirmasi unit","ユニットを確定","Antrenmanı onayla","세션 확정"],
"Satzpause — Aufnahme angehalten":["Rest — recording paused","组间休息——录制已暂停","विराम — रिकॉर्डिंग रुकी","Descanso — grabación en pausa","Repos — enregistrement en pause","استراحة — التسجيل متوقف","বিরতি — রেকর্ডিং থেমে আছে","Отдых — запись на паузе","Descanso — gravação pausada","وقفہ — ریکارڈنگ رکی ہوئی","Istirahat — perekaman dijeda","休憩 — 録画一時停止","Mola — kayıt duraklatıldı","휴식 — 녹화 일시정지"],
"Weiter ▶":["Continue ▶","继续 ▶","जारी रखें ▶","Continuar ▶","Continuer ▶","متابعة ▶","চালিয়ে যান ▶","Продолжить ▶","Continuar ▶","جاری رکھیں ▶","Lanjut ▶","再開 ▶","Devam ▶","계속 ▶"],
"Aufnahme abbrechen?":["Cancel recording?","取消录制？","रिकॉर्डिंग रद्द करें?","¿Cancelar la grabación?","Annuler l'enregistrement ?","إلغاء التسجيل؟","রেকর্ডিং বাতিল করবেন?","Отменить запись?","Cancelar gravação?","ریکارڈنگ منسوخ کریں؟","Batalkan perekaman?","録画を中止しますか？","Kayıt iptal edilsin mi?","녹화를 취소할까요?"],
"Dein Video wird verworfen und die Einheit":["Your video will be discarded and the unit","你的视频将被丢弃，训练","आपका वीडियो हटेगा और यूनिट","Tu vídeo se descartará y la unidad","Ta vidéo sera supprimée et la séance","سيتم تجاهل الفيديو والتمرين","আপনার ভিডিও বাতিল হবে এবং ইউনিট","Видео будет удалено, а тренировка","Seu vídeo será descartado e o treino","آپ کی ویڈیو ضائع ہو جائے گی اور یونٹ","Videomu akan dibuang dan unit","動画は破棄され、ユニットは","Videon silinecek ve antrenman","영상은 폐기되며 세션은"],
"nicht gewertet":["not counted","不计入","गिनी नहीं जाएगी","no contará","non comptée","لن يُحتسب","গণনা হবে না","не засчитана","não contará","شمار نہیں ہوگا","tidak dihitung","カウントされません","sayılmayacak","집계되지 않음"],
". Bist du sicher?":[". Are you sure?","。确定吗？","। पक्का?",". ¿Estás seguro?"," . Tu es sûr ?",". هل أنت متأكد؟","। আপনি কি নিশ্চিত?",". Вы уверены?",". Tem certeza?","۔ کیا آپ کو یقین ہے؟",". Yakin?","。よろしいですか？",". Emin misin?",". 확실한가요?"],
"Weiter aufnehmen":["Keep recording","继续录制","रिकॉर्डिंग जारी रखें","Seguir grabando","Continuer l'enregistrement","متابعة التسجيل","রেকর্ডিং চালিয়ে যান","Продолжить запись","Continuar gravando","ریکارڈنگ جاری رکھیں","Lanjutkan merekam","録画を続ける","Kayda devam et","계속 녹화"],
"Ja, abbrechen":["Yes, cancel","是，取消","हाँ, रद्द करें","Sí, cancelar","Oui, annuler","نعم، إلغاء","হ্যাঁ, বাতিল","Да, отменить","Sim, cancelar","ہاں، منسوخ کریں","Ya, batalkan","はい、中止する","Evet, iptal et","네, 취소합니다"],
"Bist du wirklich sicher?":["Are you really sure?","你真的确定吗？","क्या आप सच में निश्चित हैं?","¿Seguro de verdad?","Tu es vraiment sûr ?","هل أنت متأكد حقاً؟","আপনি কি সত্যিই নিশ্চিত?","Вы точно уверены?","Tem mesmo certeza?","کیا آپ واقعی پُریقین ہیں؟","Benar-benar yakin?","本当によろしいですか？","Gerçekten emin misin?","정말 확실한가요?"],
"Du hast noch":["You still have","你还有","आपके अभी","Aún tienes","Il te reste","لا يزال لديك","আপনার এখনও","У вас ещё","Você ainda tem","آپ کے ابھی","Kamu masih","まだ","Hâlâ","아직"],
"nicht alle Sets abgehakt":["not ticked off all sets","未确认所有组","सभी सेट पूरे नहीं किए","no has marcado todas las series","pas validé toutes les séries","لم تُنهِ جميع المجموعات","সব সেট টিক করেননি","отмечены не все подходы","não marcou todas as séries","تمام سیٹس نشان زد نہیں کیے","belum mencentang semua set","全セットを完了していません","tüm setleri işaretlemedin","모든 세트를 체크하지 않음"],
". Wenn du so einreichst, wird deine Einheit von den Prüfern":[". If you submit like this, your unit will","。如果就这样提交，你的训练","। ऐसे सबमिट करने पर आपकी यूनिट",". Si lo envías así, tu unidad"," . Si tu soumets ainsi, ta séance",". إذا أرسلت هكذا، فسيكون تمرينك","। এভাবে জমা দিলে আপনার ইউনিট",". Если отправите так, вашу тренировку",". Se enviar assim, seu treino","۔ اس طرح جمع کرنے پر آپ کا یونٹ",". Jika dikirim begini, unitmu","。このまま提出すると、審査員に",". Böyle gönderirsen antrenmanın",". 이대로 제출하면 세션이"],
"höchstwahrscheinlich nicht bestätigt":["most likely not be confirmed by reviewers","很可能不会被审核员确认","समीक्षकों द्वारा शायद पुष्ट नहीं होगी","muy probablemente no será confirmada","ne sera très probablement pas validée","على الأرجح لن يتم تأكيده","সম্ভবত নিশ্চিত হবে না","скорее всего не подтвердят","muito provavelmente não será confirmado","غالباً تصدیق نہیں ہوگا","kemungkinan besar tidak dikonfirmasi","承認されない可能性が高いです","büyük olasılıkla onaylanmayacak","승인되지 않을 가능성이 높습니다"],
"Weiter trainieren":["Keep training","继续训练","ट्रेनिंग जारी रखें","Seguir entrenando","Continuer l'entraînement","متابعة التدريب","প্রশিক্ষণ চালিয়ে যান","Продолжить тренировку","Continuar treinando","تربیت جاری رکھیں","Lanjut latihan","トレーニングを続ける","Antrenmana devam et","계속 훈련"],
"Trotzdem einreichen":["Submit anyway","仍然提交","फिर भी सबमिट करें","Enviar igualmente","Soumettre quand même","إرسال على أي حال","তবুও জমা দিন","Всё равно отправить","Enviar mesmo assim","پھر بھی جمع کریں","Tetap kirim","それでも提出","Yine de gönder","그래도 제출"],
"Beschwerde einreichen":["File a complaint","提交投诉","शिकायत दर्ज करें","Presentar una queja","Déposer une plainte","تقديم شكوى","অভিযোগ দাখিল করুন","Подать жалобу","Registrar reclamação","شکایت درج کریں","Ajukan keluhan","異議を申し立てる","Şikâyet et","이의 제기"],
"Der Admin prüft dein Video und das Review-Ergebnis.":["The admin reviews your video and the result.","管理员会审核你的视频和评审结果。","एडमिन आपका वीडियो और परिणाम जांचेगा।","El admin revisa tu vídeo y el resultado.","L'admin vérifie ta vidéo et le résultat.","يراجع المشرف الفيديو والنتيجة.","অ্যাডমিন আপনার ভিডিও ও ফলাফল পরীক্ষা করবে।","Админ проверит ваше видео и результат.","O admin analisa seu vídeo e o resultado.","ایڈمن آپ کی ویڈیو اور نتیجہ جانچے گا۔","Admin meninjau videomu dan hasilnya.","管理者が動画と審査結果を確認します。","Yönetici videonu ve sonucu inceler.","관리자가 영상과 결과를 검토합니다."],
"Achtung:":["Warning:","注意：","ध्यान दें:","Atención:","Attention :","تنبيه:","সতর্কতা:","Внимание:","Atenção:","توجہ:","Perhatian:","注意：","Dikkat:","주의:"],
"Unberechtigte Beschwerden geben 1 Penalty — bei 3 Penaltys wird dein Konto blockiert.":["Unjustified complaints earn 1 penalty — at 3 penalties your account gets blocked.","无理投诉将获得1次处罚——满3次账户将被封锁。","अनुचित शिकायत पर 1 पेनल्टी — 3 पर खाता ब्लॉक।","Las quejas injustificadas dan 1 penalización; con 3 se bloquea tu cuenta.","Une plainte injustifiée donne 1 pénalité — à 3, ton compte est bloqué.","الشكاوى غير المبررة تمنح عقوبة واحدة — عند 3 يُحظر حسابك.","অযৌক্তিক অভিযোগে ১ পেনাল্টি — ৩ হলে অ্যাকাউন্ট ব্লক।","Необоснованные жалобы дают 1 штраф — при 3 аккаунт блокируется.","Reclamações injustas dão 1 penalidade — com 3 sua conta é bloqueada.","بلاجواز شکایات پر 1 پنالٹی — 3 پر اکاؤنٹ بلاک۔","Keluhan tak berdasar memberi 1 penalti — pada 3 akunmu diblokir.","不当な異議は1ペナルティ — 3回でアカウント停止。","Haksız şikâyetler 1 ceza verir — 3 cezada hesabın engellenir.","부당한 이의는 페널티 1회 — 3회면 계정 차단."],
"Was ist aus deiner Sicht falsch gelaufen?":["What went wrong in your view?","你认为哪里出了问题？","आपके अनुसार क्या गलत हुआ?","¿Qué salió mal según tú?","Qu'est-ce qui s'est mal passé selon toi ?","ما الخطأ الذي حدث برأيك؟","আপনার মতে কী ভুল হয়েছে?","Что, по-вашему, пошло не так?","O que deu errado na sua visão?","آپ کے خیال میں کیا غلط ہوا؟","Menurutmu apa yang salah?","何が問題だったと思いますか？","Sence ne yanlış gitti?","무엇이 잘못되었나요?"],
"Einreichen":["Submit","提交","सबमिट करें","Enviar","Soumettre","إرسال","জমা দিন","Отправить","Enviar","جمع کریں","Kirim","送信","Gönder","제출"],
"Auszahlen":["Withdraw","提现","निकासी","Retirar","Retirer","سحب","উত্তোলন","Вывести","Sacar","نکالیں","Tarik","出金","Para çek","출금"],
"Auszahlung bestätigen":["Confirm payout","确认提现","भुगतान की पुष्टि करें","Confirmar retiro","Confirmer le versement","تأكيد السحب","পেমেন্ট নিশ্চিত করুন","Подтвердить выплату","Confirmar saque","ادائیگی کی تصدیق کریں","Konfirmasi penarikan","出金を確定","Ödemeyi onayla","출금 확정"],
"werden auf dein Konto (IBAN ****4821) überwiesen.":["will be transferred to your account (IBAN ****4821).","将转入你的账户（IBAN ****4821）。","आपके खाते (IBAN ****4821) में भेजे जाएंगे।","se transferirán a tu cuenta (IBAN ****4821).","seront virés sur ton compte (IBAN ****4821).","سيتم تحويلها إلى حسابك (IBAN ****4821).","আপনার অ্যাকাউন্টে (IBAN ****4821) পাঠানো হবে।","будут переведены на ваш счёт (IBAN ****4821).","serão transferidos para sua conta (IBAN ****4821).","آپ کے اکاؤنٹ (IBAN ****4821) میں منتقل ہوں گے۔","akan ditransfer ke rekeningmu (IBAN ****4821).","口座（IBAN ****4821）に振り込まれます。","hesabına (IBAN ****4821) aktarılacak.","계좌(IBAN ****4821)로 이체됩니다."],
"Bewerte deine Erfahrung!":["Rate your experience!","评价你的体验！","अपना अनुभव रेट करें!","¡Valora tu experiencia!","Note ton expérience !","قيّم تجربتك!","আপনার অভিজ্ঞতা রেট করুন!","Оцените ваш опыт!","Avalie sua experiência!","اپنے تجربے کی درجہ بندی کریں!","Nilai pengalamanmu!","体験を評価してください！","Deneyimini değerlendir!","경험을 평가해주세요!"],
"Die Mobile-App ist noch nicht in den Stores verfügbar. Sobald sie veröffentlicht ist, kannst du RepVerify hier bewerten.":["The mobile app isn't in the stores yet. Once it's published you can rate RepVerify here.","移动应用尚未上架。发布后你可以在这里评价 RepVerify。","मोबाइल ऐप अभी स्टोर में नहीं है। प्रकाशित होते ही आप यहां रेट कर सकेंगे।","La app móvil aún no está en las tiendas. Cuando se publique podrás valorar RepVerify aquí.","L'app mobile n'est pas encore dans les stores. Dès sa sortie, tu pourras noter RepVerify ici.","التطبيق غير متوفر في المتاجر بعد. عند نشره يمكنك تقييم RepVerify هنا.","মোবাইল অ্যাপ এখনো স্টোরে নেই। প্রকাশিত হলে এখানে রেট করতে পারবেন।","Мобильное приложение ещё не в магазинах. После публикации сможете оценить RepVerify здесь.","O app móvel ainda não está nas lojas. Assim que publicado, você poderá avaliar o RepVerify aqui.","موبائل ایپ ابھی اسٹورز میں نہیں۔ شائع ہوتے ہی آپ یہاں درجہ بندی کر سکیں گے۔","Aplikasi seluler belum ada di toko. Setelah rilis kamu bisa menilai RepVerify di sini.","モバイルアプリはまだストアにありません。公開後にここで評価できます。","Mobil uygulama henüz mağazalarda değil. Yayınlanınca RepVerify'ı burada değerlendirebilirsin.","모바일 앱은 아직 스토어에 없습니다. 출시되면 여기서 평가할 수 있어요."],
"Alles klar":["Got it","知道了","ठीक है","Entendido","Compris","حسناً","ঠিক আছে","Понятно","Entendi","ٹھیک ہے","Mengerti","了解","Anladım","알겠습니다"],
"Beschreibe das Problem so genau wie möglich…":["Describe the problem as precisely as possible…","请尽量详细描述问题…","समस्या यथासंभव विस्तार से बताएं…","Describe el problema con el mayor detalle posible…","Décris le problème le plus précisément possible…","صف المشكلة بأكبر قدر من الدقة…","সমস্যাটি যত সম্ভব বিস্তারিত লিখুন…","Опишите проблему как можно точнее…","Descreva o problema com o máximo de detalhes…","مسئلہ جتنا ممکن ہو تفصیل سے بیان کریں…","Jelaskan masalah sedetail mungkin…","問題をできるだけ詳しく説明してください…","Sorunu olabildiğince ayrıntılı anlat…","문제를 최대한 자세히 설명해주세요…"],
"Gib nur Details an, die für das Problem relevant sind.":["Only include details relevant to the problem.","只提供与问题相关的细节。","केवल समस्या से जुड़ी जानकारी दें।","Incluye solo detalles relevantes para el problema.","N'indique que les détails pertinents.","اذكر فقط التفاصيل المتعلقة بالمشكلة.","শুধু প্রাসঙ্গিক বিবরণ দিন।","Указывайте только относящиеся к проблеме детали.","Inclua apenas detalhes relevantes.","صرف مسئلے سے متعلق تفصیلات دیں۔","Sertakan hanya detail yang relevan.","問題に関係する情報のみ記入してください。","Sadece sorunla ilgili ayrıntıları belirt.","문제와 관련된 내용만 적어주세요."],
"Senden":["Send","发送","भेजें","Enviar","Envoyer","إرسال","পাঠান","Отправить","Enviar","بھیجیں","Kirim","送信","Gönder","보내기"],
"Deine Idee oder dein Feature-Wunsch…":["Your idea or feature request…","你的想法或功能需求…","आपका सुझाव या फीचर अनुरोध…","Tu idea o petición de función…","Ton idée ou demande de fonctionnalité…","فكرتك أو الميزة المطلوبة…","আপনার আইডিয়া বা ফিচার অনুরোধ…","Ваша идея или запрос функции…","Sua ideia ou pedido de recurso…","آپ کا خیال یا فیچر کی خواہش…","Ide atau permintaan fiturmu…","アイデアや機能要望…","Fikrin veya özellik isteğin…","아이디어 또는 기능 요청…"],
"Bitte reiche nur relevante und wichtige Informationen ein.":["Please only submit relevant and important information.","请只提交相关且重要的信息。","कृपया केवल प्रासंगिक और महत्वपूर्ण जानकारी भेजें।","Envía solo información relevante e importante.","Merci de ne soumettre que des informations pertinentes.","يرجى إرسال المعلومات المهمة وذات الصلة فقط.","শুধু প্রাসঙ্গিক ও গুরুত্বপূর্ণ তথ্য দিন।","Отправляйте только важную и относящуюся к делу информацию.","Envie apenas informações relevantes e importantes.","براہ کرم صرف متعلقہ اور اہم معلومات جمع کریں۔","Harap kirim hanya info yang relevan dan penting.","関連する重要な情報のみ送信してください。","Lütfen yalnızca ilgili ve önemli bilgileri gönder.","관련 있고 중요한 정보만 제출해주세요."],
"Nur App entfernen?":["Remove app only?","仅移除应用？","सिर्फ ऐप हटाएं?","¿Quitar solo la app?","Retirer seulement l'app ?","إزالة التطبيق فقط؟","শুধু অ্যাপ সরাবেন?","Удалить только приложение?","Remover só o app?","صرف ایپ ہٹائیں؟","Hapus aplikasi saja?","アプリのみ削除？","Sadece uygulama kaldırılsın mı?","앱만 제거할까요?"],
"Dein Konto und alle Daten":["Your account and all data","你的账户和所有数据","आपका खाता और सारा डेटा","Tu cuenta y todos los datos","Ton compte et toutes les données","حسابك وجميع البيانات","আপনার অ্যাকাউন্ট ও সব ডেটা","Ваш аккаунт и все данные","Sua conta e todos os dados","آپ کا اکاؤنٹ اور تمام ڈیٹا","Akunmu dan semua data","アカウントとすべてのデータは","Hesabın ve tüm veriler","계정과 모든 데이터는"],
"bleiben erhalten":["are kept","将保留","सुरक्षित रहेंगे","se conservan","sont conservés","تبقى محفوظة","সংরক্ষিত থাকবে","сохраняются","são mantidos","محفوظ رہیں گے","tetap tersimpan","保持されます","korunur","유지됩니다"],
". Du kannst dich jederzeit wieder anmelden.":[". You can sign back in anytime.","。你可以随时重新登录。","। आप कभी भी फिर से साइन इन कर सकते हैं।",". Puedes volver a iniciar sesión cuando quieras."," . Tu peux te reconnecter à tout moment.",". يمكنك تسجيل الدخول مجدداً في أي وقت.","। যেকোনো সময় আবার সাইন ইন করতে পারবেন।",". Вы можете войти снова в любое время.",". Você pode entrar novamente quando quiser.","۔ آپ کسی بھی وقت دوبارہ سائن ان کر سکتے ہیں۔",". Kamu bisa masuk lagi kapan saja.","。いつでも再ログインできます。",". İstediğin zaman tekrar giriş yapabilirsin.",". 언제든 다시 로그인할 수 있습니다."],
"Diese Aktion ist":["This action is","此操作","यह क्रिया","Esta acción es","Cette action est","هذا الإجراء","এই কাজটি","Это действие","Esta ação é","یہ عمل","Tindakan ini","この操作は","Bu işlem","이 작업은"],
"endgültig":["final","不可逆","स्थायी","definitiva","définitive","نهائي","চূড়ান্ত","необратимо","definitiva","حتمی","permanen","取り消し不能","kesindir","최종적"],
"und kann nicht rückgängig gemacht werden.":["and cannot be undone.","且无法撤销。","और वापस नहीं हो सकती।","y no se puede deshacer.","et ne peut pas être annulée.","ولا يمكن التراجع عنه.","এবং ফেরানো যাবে না।","и не может быть отменено.","e não pode ser desfeita.","اور واپس نہیں ہو سکتا۔","dan tidak dapat dibatalkan.","、元に戻せません。","ve geri alınamaz.","이며 되돌릴 수 없습니다."],
"Ja, löschen":["Yes, delete","是，删除","हाँ, हटाएं","Sí, eliminar","Oui, supprimer","نعم، احذف","হ্যাঁ, মুছুন","Да, удалить","Sim, excluir","ہاں، حذف کریں","Ya, hapus","はい、削除する","Evet, sil","네, 삭제합니다"],
"Nein":["No","否","नहीं","No","Non","لا","না","Нет","Não","نہیں","Tidak","いいえ","Hayır","아니요"],
"So funktionieren Rewards":["How rewards work","奖励机制说明","रिवॉर्ड ऐसे काम करते हैं","Así funcionan las recompensas","Fonctionnement des récompenses","كيف تعمل المكافآت","রিওয়ার্ড যেভাবে কাজ করে","Как работают награды","Como funcionam as recompensas","انعامات ایسے کام کرتے ہیں","Cara kerja hadiah","リワードの仕組み","Ödüller nasıl çalışır","리워드 작동 방식"],
"Abo kostet 10 €. Monat komplett (30/30) → 8 € zurück.":["Subscription costs 10. Complete the month (30/30) → 8 back.","订阅费10。完成整月（30/30）→ 返还8。","सदस्यता 10 की। पूरा महीना (30/30) → 8 वापस।","La suscripción cuesta 10. Mes completo (30/30) → 8 de vuelta.","L'abonnement coûte 10. Mois complet (30/30) → 8 remboursés.","الاشتراك 10. أكمل الشهر (30/30) ← استرد 8.","সাবস্ক্রিপশন ১০। পুরো মাস (৩০/৩০) → ৮ ফেরত।","Подписка стоит 10. Полный месяц (30/30) → 8 назад.","Assinatura custa 10. Mês completo (30/30) → 8 de volta.","سبسکرپشن 10 کی۔ مکمل مہینہ (30/30) ← 8 واپس۔","Langganan 10. Bulan penuh (30/30) → 8 kembali.","サブスクは10。月間コンプリート（30/30）→8返金。","Abonelik 10. Ayı tamamla (30/30) → 8 iade.","구독료 10. 한 달 완주(30/30) → 8 환급."],
"Jede gewonnene Ranking-Position bringt +0,25 € Bonus.":["Each ranking position gained earns a +0.25 bonus.","每上升一个排名 +0.25 奖励。","हर रैंक बढ़ने पर +0.25 बोनस।","Cada puesto ganado da +0,25 de bono.","Chaque place gagnée rapporte +0,25 de bonus.","كل مركز مكتسب يمنح مكافأة +0.25.","প্রতি অর্জিত র‍্যাঙ্কে +০.২৫ বোনাস।","Каждая занятая позиция даёт бонус +0,25.","Cada posição ganha rende +0,25 de bônus.","ہر حاصل شدہ پوزیشن پر ‎+0.25 بونس۔","Setiap posisi naik memberi bonus +0,25.","順位が1つ上がるごとに+0.25ボーナス。","Kazanılan her sıra +0,25 bonus getirir.","순위 상승당 +0.25 보너스."],
"Monatliche Erstattung":["Monthly refund","每月返还","मासिक रिफंड","Reembolso mensual","Remboursement mensuel","الاسترداد الشهري","মাসিক ফেরত","Месячный возврат","Reembolso mensal","ماہانہ واپسی","Pengembalian bulanan","月次返金","Aylık iade","월간 환급"],
"Verfügbares Guthaben":["Available balance","可用余额","उपलब्ध बैलेंस","Saldo disponible","Solde disponible","الرصيد المتاح","উপলব্ধ ব্যালেন্স","Доступный баланс","Saldo disponível","دستیاب بیلنس","Saldo tersedia","利用可能残高","Kullanılabilir bakiye","사용 가능 잔액"],
"Lebenszeit gesamt verdient":["Lifetime total earned","累计总收入","कुल कमाई","Total ganado histórico","Total gagné à vie","إجمالي الأرباح","মোট আয়","Всего заработано","Total ganho","کل کمائی","Total diperoleh","累計獲得額","Toplam kazanç","누적 수익"],
"Ranking-Bonus":["Ranking bonus","排名奖励","रैंकिंग बोनस","Bono de ranking","Bonus de classement","مكافأة التصنيف","র‍্যাঙ্কিং বোনাস","Бонус рейтинга","Bônus de ranking","درجہ بندی بونس","Bonus peringkat","ランキングボーナス","Sıralama bonusu","랭킹 보너스"],
"Balance-Details":["Balance details","余额明细","बैलेंस विवरण","Detalles del saldo","Détails du solde","تفاصيل الرصيد","ব্যালেন্স বিবরণ","Детали баланса","Detalhes do saldo","بیلنس کی تفصیلات","Detail saldo","残高の詳細","Bakiye detayları","잔액 상세"],
"Alle":["All","全部","सभी","Todo","Tout","الكل","সব","Все","Tudo","سب","Semua","すべて","Tümü","전체"],
"Einnahmen":["Income","收入","आय","Ingresos","Revenus","الإيرادات","আয়","Доходы","Entradas","آمدنی","Pemasukan","収入","Gelirler","수입"],
"Abzüge":["Deductions","支出","कटौती","Deducciones","Déductions","الخصومات","কর্তন","Списания","Saídas","کٹوتیاں","Pengeluaran","支出","Kesintiler","공제"],
"Auszahlung ab 8,00 € möglich":["Withdrawal available from 8.00","满8.00可提现","8.00 से निकासी संभव","Retiro posible desde 8,00","Retrait possible dès 8,00","السحب متاح من 8.00","৮.০০ থেকে উত্তোলন সম্ভব","Вывод от 8,00","Saque a partir de 8,00","8.00 سے نکاسی ممکن","Penarikan mulai 8,00","8.00から出金可能","8,00'dan itibaren çekim","8.00부터 출금 가능"],
"Juni-Rankings":["June rankings","六月排行榜","जून रैंकिंग","Rankings de junio","Classements de juin","تصنيفات يونيو","জুন র‍্যাঙ্কিং","Рейтинг за июнь","Rankings de junho","جون کی درجہ بندی","Peringkat Juni","6月のランキング","Haziran sıralaması","6월 랭킹"],
"Ziel 10":["Goal 10","目标 10","लक्ष्य 10","Meta 10","Objectif 10","الهدف 10","লক্ষ্য ১০","Цель 10","Meta 10","ہدف 10","Target 10","目標10","Hedef 10","목표 10"],
"Punkte · Ziel 10 · Max":["Points · goal 10 · max","分数 · 目标10 · 上限","अंक · लक्ष्य 10 · अधिकतम","Puntos · meta 10 · máx","Points · objectif 10 · max","نقاط · الهدف 10 · الحد الأقصى","পয়েন্ট · লক্ষ্য ১০ · সর্বোচ্চ","Очки · цель 10 · макс","Pontos · meta 10 · máx","پوائنٹس · ہدف 10 · زیادہ سے زیادہ","Poin · target 10 · maks","ポイント・目標10・最大","Puan · hedef 10 · maks","포인트 · 목표 10 · 최대"]
});
Object.assign(window.I18N_SRC,{
"Keine offenen Prüfanfragen — stark! 💪":["No open review requests — nice! 💪","没有待审核请求——棒！💪","कोई लंबित समीक्षा नहीं — बढ़िया! 💪","Sin solicitudes pendientes — ¡genial! 💪","Aucune demande en attente — bravo ! 💪","لا توجد طلبات مراجعة — رائع! 💪","কোনো মুলতুবি অনুরোধ নেই — দারুণ! 💪","Нет открытых проверок — отлично! 💪","Sem pedidos pendentes — ótimo! 💪","کوئی زیر التوا درخواست نہیں — زبردست! 💪","Tidak ada permintaan tinjauan — mantap! 💪","未処理のリクエストなし — すばらしい！💪","Bekleyen inceleme yok — süper! 💪","대기 중인 검증 없음 — 좋아요! 💪"],
"▶ Video laden (nur für dich sichtbar)":["▶ Load video (visible only to you)","▶ 加载视频（仅你可见）","▶ वीडियो लोड करें (सिर्फ आपको दिखेगा)","▶ Cargar vídeo (solo visible para ti)","▶ Charger la vidéo (visible par toi seul)","▶ تحميل الفيديو (مرئي لك فقط)","▶ ভিডিও লোড করুন (শুধু আপনি দেখবেন)","▶ Загрузить видео (видно только вам)","▶ Carregar vídeo (visível só para você)","▶ ویڈیو لوڈ کریں (صرف آپ کو نظر آئے گی)","▶ Muat video (hanya terlihat olehmu)","▶ 動画を読み込む（自分のみ閲覧可）","▶ Videoyu yükle (sadece sana görünür)","▶ 영상 불러오기 (나만 볼 수 있음)"],
"Video wird geladen…":["Loading video…","视频加载中…","वीडियो लोड हो रहा है…","Cargando vídeo…","Chargement de la vidéo…","جارٍ تحميل الفيديو…","ভিডিও লোড হচ্ছে…","Видео загружается…","Carregando vídeo…","ویڈیو لوڈ ہو رہی ہے…","Memuat video…","動画を読み込み中…","Video yükleniyor…","영상 불러오는 중…"],
"Ablehnen":["Reject","拒绝","अस्वीकार","Rechazar","Refuser","رفض","প্রত্যাখ্যান","Отклонить","Rejeitar","مسترد","Tolak","却下","Reddet","거부"],
"Bestätigen":["Confirm","确认","पुष्टि करें","Confirmar","Valider","تأكيد","নিশ্চিত করুন","Подтвердить","Confirmar","تصدیق کریں","Konfirmasi","承認","Onayla","승인"],
"Sets zählen":["count sets","数组数","सेट गिनें","contar series","compter les séries","عدّ المجموعات","সেট গুনুন","считайте подходы","contar séries","سیٹ گنیں","hitung set","セットを数える","setleri say","세트 세기"],
"Fertig!":["Done!","完成！","हो गया!","¡Listo!","Terminé !","تم!","সম্পন্ন!","Готово!","Pronto!","مکمل!","Selesai!","完了！","Bitti!","완료!"],
"Einheit bestätigen, um abzuschließen":["Confirm the unit to finish","确认训练以完成","समाप्त करने के लिए यूनिट पुष्ट करें","Confirma la unidad para terminar","Valide la séance pour terminer","أكد التمرين للإنهاء","শেষ করতে ইউনিট নিশ্চিত করুন","Подтвердите тренировку для завершения","Confirme o treino para finalizar","مکمل کرنے کے لیے یونٹ کی تصدیق کریں","Konfirmasi unit untuk menyelesaikan","確定して終了する","Bitirmek için antrenmanı onayla","완료하려면 세션을 확정하세요"],
"Alles in Ordnung":["All good","一切正常","सब ठीक","Todo en orden","Tout est bon","كل شيء على ما يرام","সব ঠিক আছে","Всё в порядке","Tudo certo","سب ٹھیک","Semua beres","問題なし","Her şey yolunda","이상 없음"],
"Nicht bestätigt":["Not confirmed","未确认","पुष्ट नहीं","No confirmada","Non validée","غير مؤكد","নিশ্চিত নয়","Не подтверждено","Não confirmado","تصدیق نہیں ہوئی","Tidak dikonfirmasi","未承認","Onaylanmadı","미승인"],
"Prüfer":["Reviewer","审核员","समीक्षक","Revisor","Vérificateur","المراجع","পরীক্ষক","Проверяющий","Revisor","جائزہ کار","Peninjau","審査員","İnceleyici","검토자"],
"gezählt":["counted","已计数","गिना","contado","compté","المعدود","গণনাকৃত","насчитано","contado","شمار شدہ","dihitung","カウント","sayılan","집계"],
"Urteil":["Verdict","判定","निर्णय","Veredicto","Verdict","الحكم","রায়","Вердикт","Veredicto","فیصلہ","Putusan","判定","Karar","판정"],
"Bestätigt ✓":["Confirmed ✓","已确认 ✓","पुष्ट ✓","Confirmado ✓","Validé ✓","مؤكد ✓","নিশ্চিত ✓","Подтверждено ✓","Confirmado ✓","تصدیق شدہ ✓","Dikonfirmasi ✓","承認 ✓","Onaylandı ✓","승인 ✓"],
"Abgelehnt ✗":["Rejected ✗","已拒绝 ✗","अस्वीकृत ✗","Rechazado ✗","Refusé ✗","مرفوض ✗","প্রত্যাখ্যাত ✗","Отклонено ✗","Rejeitado ✗","مسترد ✗","Ditolak ✗","却下 ✗","Reddedildi ✗","거부 ✗"],
"Nicht einverstanden? 24 h Zeit — danach wird das Video gelöscht.":["Disagree? 24 h to act — then the video is deleted.","不同意？24小时内处理——之后视频将被删除。","असहमत? 24 घंटे — फिर वीडियो हट जाएगा।","¿No estás de acuerdo? 24 h — luego el vídeo se elimina.","Pas d'accord ? 24 h — ensuite la vidéo est supprimée.","غير موافق؟ 24 ساعة — بعدها يُحذف الفيديو.","একমত নন? ২৪ ঘণ্টা — এরপর ভিডিও মুছে যাবে।","Не согласны? 24 ч — потом видео будет удалено.","Discorda? 24 h — depois o vídeo é excluído.","متفق نہیں؟ 24 گھنٹے — پھر ویڈیو حذف ہو جائے گی۔","Tidak setuju? 24 jam — lalu video dihapus.","不服がある場合は24時間以内に — その後動画は削除されます。","Katılmıyor musun? 24 saat — sonra video silinir.","동의하지 않나요? 24시간 후 영상이 삭제됩니다."],
"Beschwerde":["Complaint","投诉","शिकायत","Queja","Plainte","شكوى","অভিযোগ","Жалоба","Reclamação","شکایت","Keluhan","異議","Şikâyet","이의"],
"Beschwerde:":["Complaint:","投诉：","शिकायत:","Queja:","Plainte :","الشكوى:","অভিযোগ:","Жалоба:","Reclamação:","شکایت:","Keluhan:","異議：","Şikâyet:","이의:"],
"wird vom Admin geprüft":["under admin review","管理员审核中","एडमिन जांच रहा है","en revisión del admin","en cours d'examen par l'admin","قيد مراجعة المشرف","অ্যাডমিন পর্যালোচনা করছে","проверяется админом","em análise pelo admin","ایڈمن جائزہ لے رہا ہے","sedang ditinjau admin","管理者が確認中","yönetici inceliyor","관리자 검토 중"],
"berechtigt":["justified","成立","उचित","justificada","justifiée","مبررة","যৌক্তিক","обоснована","procedente","جائز","berdasar","正当","haklı","정당함"],
"unberechtigt (+1 Penalty)":["unjustified (+1 penalty)","不成立（+1处罚）","अनुचित (+1 पेनल्टी)","injustificada (+1 penalización)","injustifiée (+1 pénalité)","غير مبررة (+1 عقوبة)","অযৌক্তিক (+১ পেনাল্টি)","необоснована (+1 штраф)","improcedente (+1 penalidade)","بلاجواز (+1 پنالٹی)","tak berdasar (+1 penalti)","不当（+1ペナルティ）","haksız (+1 ceza)","부당함 (+1 페널티)"],
"Jetzt aufsteigen ↑":["Level up now ↑","立即晋级 ↑","अभी आगे बढ़ें ↑","Subir ahora ↑","Monter maintenant ↑","ترقَّ الآن ↑","এখনই উন্নীত হন ↑","Повыситься сейчас ↑","Subir agora ↑","ابھی ترقی کریں ↑","Naik sekarang ↑","今すぐ昇格 ↑","Şimdi yüksel ↑","지금 승급 ↑"],
"Vielfalt — Übungen deiner Stufe auf Level 2+":["Variety — your tier's exercises at level 2+","多样性——本阶段动作达2级以上","विविधता — आपकी स्टेज के व्यायाम लेवल 2+","Variedad — ejercicios de tu nivel en 2+","Variété — exercices de ton palier au niveau 2+","التنويع — تمارين مستواك في المستوى +2","বৈচিত্র্য — আপনার স্তরের ব্যায়াম লেভেল ২+","Разнообразие — упражнения ступени на ур. 2+","Variedade — exercícios do seu nível em 2+","تنوع — آپ کے درجے کی مشقیں لیول 2+","Variasi — latihan tingkatmu di level 2+","バリエーション — 現ステージの種目をLv2以上に","Çeşitlilik — kademendeki hareketler seviye 2+","다양성 — 현재 단계 운동 레벨 2+"],
"Härte — davon rote (schwere) Übungen":["Grit — of those, red (hard) exercises","强度——其中的红色（高难度）动作","कठोरता — उनमें लाल (कठिन) व्यायाम","Dureza — de ellos, ejercicios rojos (difíciles)","Difficulté — dont exercices rouges (durs)","الصعوبة — منها تمارين حمراء (صعبة)","কঠোরতা — এর মধ্যে লাল (কঠিন) ব্যায়াম","Сложность — из них красные (тяжёлые)","Dificuldade — desses, exercícios vermelhos (difíceis)","سختی — ان میں سرخ (مشکل) مشقیں","Kekuatan — di antaranya latihan merah (sulit)","ハード — うち赤（高難度）種目","Zorluk — bunlardan kırmızı (zor) hareketler","강도 — 그중 빨간(어려운) 운동"],
"Konstanz — abgeschlossene Einheiten gesamt":["Consistency — total completed units","坚持——累计完成训练","निरंतरता — कुल पूर्ण यूनिट","Constancia — unidades completadas en total","Régularité — total des séances terminées","الاستمرارية — إجمالي التمارين المكتملة","ধারাবাহিকতা — মোট সম্পন্ন ইউনিট","Постоянство — всего завершённых тренировок","Consistência — total de treinos concluídos","تسلسل — کل مکمل یونٹس","Konsistensi — total unit selesai","継続 — 累計完了ユニット","İstikrar — toplam tamamlanan antrenman","꾸준함 — 총 완료 세션"],
"Trainiere breit, nimm regelmäßig rote Übungen mit und bleib dran — dann schaltet sich die nächste Stufe frei.":["Train broadly, include red exercises regularly and keep going — the next tier will unlock.","广泛训练，常做红色动作并坚持——下一阶段就会解锁。","विविध ट्रेनिंग करें, नियमित लाल व्यायाम करें और लगे रहें — अगली स्टेज खुल जाएगी।","Entrena variado, incluye ejercicios rojos con regularidad y sigue así: se desbloqueará el siguiente nivel.","Entraîne-toi varié, ajoute régulièrement des exercices rouges et persévère — le palier suivant se débloquera.","تدرّب بتنوع وأدرج التمارين الحمراء بانتظام وواصل — سيُفتح المستوى التالي.","বৈচিত্র্যময় প্রশিক্ষণ নিন, নিয়মিত লাল ব্যায়াম করুন — পরের স্তর খুলবে।","Тренируйтесь разнообразно, регулярно берите красные упражнения — следующая ступень откроется.","Treine variado, inclua exercícios vermelhos com frequência e continue — o próximo nível será desbloqueado.","متنوع تربیت کریں، باقاعدہ سرخ مشقیں شامل کریں — اگلا درجہ کھل جائے گا۔","Berlatih beragam, rutin sertakan latihan merah — tingkat berikutnya akan terbuka.","幅広く鍛え、赤種目を定期的に取り入れて続ければ、次のステージが解放されます。","Çeşitli çalış, düzenli kırmızı hareketler ekle ve devam et — sonraki kademe açılacak.","다양하게 훈련하고 빨간 운동을 꾸준히 하면 다음 단계가 열립니다."],
"Du bist auf der höchsten freigeschalteten Stufe — Elite kommt bald.":["You're at the highest unlocked tier — Elite is coming soon.","你已达最高解锁阶段——精英级即将推出。","आप उच्चतम स्टेज पर हैं — एलीट जल्द आएगा।","Estás en el nivel más alto desbloqueado — Elite llega pronto.","Tu es au palier le plus élevé — Elite arrive bientôt.","أنت في أعلى مستوى متاح — Elite قريباً.","আপনি সর্বোচ্চ স্তরে আছেন — এলিট শীঘ্রই আসছে।","Вы на высшей открытой ступени — Elite скоро.","Você está no nível mais alto — Elite em breve.","آپ اعلیٰ ترین درجے پر ہیں — ایلیٹ جلد آرہا ہے۔","Kamu di tingkat tertinggi — Elite segera hadir.","最高ステージに到達 — Eliteは近日公開。","En yüksek kademedesin — Elite yakında.","최고 단계입니다 — 엘리트가 곧 출시됩니다."],
"Ziel erreicht ✓":["Goal reached ✓","已达目标 ✓","लक्ष्य पूरा ✓","Meta lograda ✓","Objectif atteint ✓","تحقق الهدف ✓","লক্ষ্য অর্জিত ✓","Цель достигнута ✓","Meta atingida ✓","ہدف مکمل ✓","Target tercapai ✓","目標達成 ✓","Hedefe ulaşıldı ✓","목표 달성 ✓"],
"unter Ziel":["below goal","未达目标","लक्ष्य से कम","bajo la meta","sous l'objectif","دون الهدف","লক্ষ্যের নিচে","ниже цели","abaixo da meta","ہدف سے کم","di bawah target","目標未達","hedefin altında","목표 미달"],
"Monat komplett!":["Month complete!","本月完成！","महीना पूरा!","¡Mes completo!","Mois complet !","الشهر مكتمل!","মাস সম্পূর্ণ!","Месяц закрыт!","Mês completo!","مہینہ مکمل!","Bulan lengkap!","月間コンプリート！","Ay tamamlandı!","한 달 완주!"],
"Einheit zusammenstellen":["Build your unit","组合训练","यूनिट बनाएं","Componer unidad","Composer la séance","تجهيز التمرين","ইউনিট সাজান","Собрать тренировку","Montar treino","یونٹ ترتیب دیں","Susun unit","ユニットを組む","Antrenman oluştur","세션 구성"],
"Stelle deine Einheit im Programm zusammen — mindestens":["Build your unit in the program — at least","在计划中组合你的训练——至少","प्रोग्राम में यूनिट बनाएं — कम से कम","Compón tu unidad en el programa: al menos","Compose ta séance dans le programme — au moins","جهّز تمرينك في البرنامج — على الأقل","প্রোগ্রামে ইউনিট সাজান — কমপক্ষে","Соберите тренировку в программе — минимум","Monte seu treino no programa — pelo menos","پروگرام میں یونٹ بنائیں — کم از کم","Susun unitmu di program — minimal","プログラムでユニットを組む — 最低","Programda antrenmanını oluştur — en az","프로그램에서 세션을 구성하세요 — 최소"],
"Punkte":["points","分","अंक","puntos","points","نقاط","পয়েন্ট","очков","pontos","پوائنٹس","poin","ポイント","puan","포인트"],
"für einen erfolgreichen Tag.":["for a successful day.","即可完成今日目标。","एक सफल दिन के लिए।","para un día logrado.","pour une journée réussie.","ليوم ناجح.","একটি সফল দিনের জন্য।","для успешного дня.","para um dia de sucesso.","کامیاب دن کے لیے۔","untuk hari yang sukses.","で1日クリア。","başarılı bir gün için.","성공적인 하루를 위해."],
"Noch keine Übungen absolviert — starte deine erste Einheit!":["No exercises done yet — start your first unit!","还没有完成任何动作——开始你的第一次训练吧！","अभी कोई व्यायाम नहीं — पहली यूनिट शुरू करें!","Aún sin ejercicios: ¡empieza tu primera unidad!","Aucun exercice encore — lance ta première séance !","لا تمارين بعد — ابدأ تمرينك الأول!","এখনো কোনো ব্যায়াম নেই — প্রথম ইউনিট শুরু করুন!","Упражнений пока нет — начните первую тренировку!","Nenhum exercício ainda — comece seu primeiro treino!","ابھی کوئی مشق نہیں — پہلا یونٹ شروع کریں!","Belum ada latihan — mulai unit pertamamu!","まだ種目なし — 最初のユニットを始めよう！","Henüz hareket yok — ilk antrenmanına başla!","아직 운동 기록 없음 — 첫 세션을 시작하세요!"],
"Heutige Einheit ist bereits aufgenommen":["Today's unit is already recorded","今日训练已录制","आज की यूनिट पहले से रिकॉर्ड है","La unidad de hoy ya está grabada","La séance du jour est déjà enregistrée","تم تسجيل تمرين اليوم بالفعل","আজকের ইউনিট ইতিমধ্যে রেকর্ড হয়েছে","Тренировка на сегодня уже записана","O treino de hoje já foi gravado","آج کا یونٹ پہلے ہی ریکارڈ ہے","Unit hari ini sudah direkam","今日のユニットは記録済み","Bugünkü antrenman zaten kaydedildi","오늘 세션은 이미 녹화됨"],
"Heute bereits eine Einheit aufgenommen":["Already recorded a unit today","今天已录制过训练","आज पहले ही यूनिट रिकॉर्ड की","Ya grabaste una unidad hoy","Séance déjà enregistrée aujourd'hui","سجلت تمريناً اليوم بالفعل","আজ ইতিমধ্যে একটি ইউনিট রেকর্ড হয়েছে","Сегодня уже записана тренировка","Já gravou um treino hoje","آج پہلے ہی ایک یونٹ ریکارڈ ہوا","Sudah merekam unit hari ini","本日は記録済みです","Bugün zaten kayıt yapıldı","오늘 이미 녹화했습니다"],
"Aufnahme verworfen":["Recording discarded","已丢弃录制","रिकॉर्डिंग हटाई गई","Grabación descartada","Enregistrement abandonné","تم تجاهل التسجيل","রেকর্ডিং বাতিল","Запись удалена","Gravação descartada","ریکارڈنگ ضائع","Rekaman dibuang","録画を破棄しました","Kayıt silindi","녹화 폐기됨"],
"Dein Browser unterstützt keine Videoaufnahme":["Your browser doesn't support video recording","你的浏览器不支持视频录制","आपका ब्राउज़र वीडियो रिकॉर्डिंग नहीं करता","Tu navegador no soporta grabación de vídeo","Ton navigateur ne permet pas l'enregistrement vidéo","متصفحك لا يدعم تسجيل الفيديو","আপনার ব্রাউজার ভিডিও রেকর্ডিং সমর্থন করে না","Ваш браузер не поддерживает запись видео","Seu navegador não suporta gravação de vídeo","آپ کا براؤزر ویڈیو ریکارڈنگ سپورٹ نہیں کرتا","Browsermu tidak mendukung perekaman video","お使いのブラウザは録画に対応していません","Tarayıcın video kaydını desteklemiyor","브라우저가 영상 녹화를 지원하지 않습니다"],
"Anzeigename aktualisiert":["Display name updated","显示名称已更新","प्रदर्शित नाम अपडेट","Nombre actualizado","Nom mis à jour","تم تحديث الاسم","নাম আপডেট হয়েছে","Имя обновлено","Nome atualizado","نام اپڈیٹ ہوا","Nama diperbarui","表示名を更新しました","Görünen ad güncellendi","표시 이름 업데이트됨"],
"Benachrichtigung aktiviert":["Notification enabled","通知已开启","सूचना चालू","Notificación activada","Notification activée","تم تفعيل الإشعار","বিজ্ঞপ্তি চালু","Уведомление включено","Notificação ativada","اطلاع فعال","Notifikasi aktif","通知をオン","Bildirim açıldı","알림 켜짐"],
"Benachrichtigung deaktiviert":["Notification disabled","通知已关闭","सूचना बंद","Notificación desactivada","Notification désactivée","تم إيقاف الإشعار","বিজ্ঞপ্তি বন্ধ","Уведомление выключено","Notificação desativada","اطلاع غیر فعال","Notifikasi mati","通知をオフ","Bildirim kapatıldı","알림 꺼짐"],
"Bitte beschreibe das Problem":["Please describe the problem","请描述问题","कृपया समस्या बताएं","Describe el problema","Décris le problème","يرجى وصف المشكلة","সমস্যাটি বর্ণনা করুন","Опишите проблему","Descreva o problema","براہ کرم مسئلہ بیان کریں","Jelaskan masalahnya","問題を説明してください","Lütfen sorunu açıkla","문제를 설명해주세요"],
"Beschwerde eingereicht — der Admin prüft den Fall":["Complaint filed — the admin will review the case","投诉已提交——管理员将审核","शिकायत दर्ज — एडमिन जांच करेगा","Queja enviada: el admin revisará el caso","Plainte déposée — l'admin examinera le cas","تم تقديم الشكوى — سيراجعها المشرف","অভিযোগ দাখিল — অ্যাডমিন পর্যালোচনা করবে","Жалоба подана — админ рассмотрит","Reclamação registrada — o admin analisará","شکایت درج — ایڈمن جائزہ لے گا","Keluhan diajukan — admin akan meninjau","異議を受け付けました — 管理者が確認します","Şikâyet alındı — yönetici inceleyecek","이의가 접수되었습니다 — 관리자가 검토합니다"],
"Bitte E-Mail eingeben":["Please enter an email","请输入邮箱","कृपया ईमेल दर्ज करें","Introduce un correo","Saisis un e-mail","يرجى إدخال البريد","ইমেল লিখুন","Введите эл. почту","Digite um e-mail","ای میل درج کریں","Masukkan email","メールを入力してください","E-posta gir","이메일을 입력하세요"],
"Abgemeldet":["Signed out","已退出","साइन आउट हुआ","Sesión cerrada","Déconnecté","تم تسجيل الخروج","সাইন আউট হয়েছে","Вы вышли","Sessão encerrada","سائن آؤٹ ہو گئے","Keluar","ログアウトしました","Çıkış yapıldı","로그아웃됨"],
"Einheit abgelehnt":["Unit rejected","训练被拒","यूनिट अस्वीकृत","Unidad rechazada","Séance refusée","تم رفض التمرين","ইউনিট প্রত্যাখ্যাত","Тренировка отклонена","Treino rejeitado","یونٹ مسترد","Unit ditolak","ユニット却下","Antrenman reddedildi","세션 거부됨"],
"Einheit bestätigt ✓":["Unit confirmed ✓","训练已确认 ✓","यूनिट पुष्ट ✓","Unidad confirmada ✓","Séance validée ✓","تم تأكيد التمرين ✓","ইউনিট নিশ্চিত ✓","Тренировка подтверждена ✓","Treino confirmado ✓","یونٹ کی تصدیق ✓","Unit dikonfirmasi ✓","ユニット承認 ✓","Antrenman onaylandı ✓","세션 승인 ✓"],
"— noch nicht gewählt":["— not chosen yet","——尚未选择","— अभी नहीं चुना","— sin elegir","— pas encore choisi","— لم يُختر بعد","— এখনো বাছা হয়নি","— ещё не выбрано","— ainda não escolhido","— ابھی منتخب نہیں","— belum dipilih","— 未選択","— henüz seçilmedi","— 아직 선택 안 함"],
"leicht":["easy","简单","आसान","fácil","facile","سهل","সহজ","легко","fácil","آسان","mudah","イージー","kolay","쉬움"],
"mittel":["medium","中等","मध्यम","medio","moyen","متوسط","মাঝারি","средне","médio","درمیانہ","sedang","ミディアム","orta","중간"],
"schwer":["hard","困难","कठिन","difícil","difficile","صعب","কঠিন","тяжело","difícil","مشکل","sulit","ハード","zor","어려움"]
});
window.I18N_PATTERNS=[
[/^noch (\d+) Einheiten$/,["$1 units left","还差 $1 次训练","$1 यूनिट बाकी","faltan $1 unidades","encore $1 séances","بقي $1 تمارين","$1 ইউনিট বাকি","осталось $1 тренировок","faltam $1 treinos","$1 یونٹ باقی","$1 unit lagi","残り$1ユニット","$1 antrenman kaldı","$1개 세션 남음"]],
[/^(\d+) ausstehend$/,["$1 pending","$1 待处理","$1 लंबित","$1 pendientes","$1 en attente","$1 معلق","$1 মুলতুবি","$1 в ожидании","$1 pendentes","$1 زیر التوا","$1 menunggu","$1 件保留中","$1 bekliyor","$1건 대기"]],
[/^(\d+) Teilnehmer$/,["$1 participants","$1 名参与者","$1 प्रतिभागी","$1 participantes","$1 participants","$1 مشاركاً","$1 অংশগ্রহণকারী","$1 участников","$1 participantes","$1 شرکاء","$1 peserta","$1人参加","$1 katılımcı","$1명 참가"]],
[/^(\d+)× genutzt$/,["used $1×","使用 $1 次","$1× किया","usado $1×","utilisé $1×","استُخدم $1×","$1× ব্যবহৃত","использовано $1×","usado $1×","$1× استعمال","dipakai $1×","$1回使用","$1× kullanıldı","$1회 사용"]],
[/^Einheit abgeschlossen — (.+) Punkte$/,["Unit completed — $1 points","训练完成——$1 分","यूनिट पूर्ण — $1 अंक","Unidad completada: $1 puntos","Séance terminée — $1 points","اكتمل التمرين — $1 نقطة","ইউনিট সম্পন্ন — $1 পয়েন্ট","Тренировка завершена — $1 очков","Treino concluído — $1 pontos","یونٹ مکمل — $1 پوائنٹس","Unit selesai — $1 poin","ユニット完了 — $1ポイント","Antrenman tamamlandı — $1 puan","세션 완료 — $1점"]],
[/^Einheit aufgenommen — (.+) Punkte$/,["Unit recorded — $1 points","训练已录制——$1 分","यूनिट रिकॉर्ड — $1 अंक","Unidad grabada: $1 puntos","Séance enregistrée — $1 points","تم تسجيل التمرين — $1 نقطة","ইউনিট রেকর্ড — $1 পয়েন্ট","Тренировка записана — $1 очков","Treino gravado — $1 pontos","یونٹ ریکارڈ — $1 پوائنٹس","Unit direkam — $1 poin","ユニット記録 — $1ポイント","Antrenman kaydedildi — $1 puan","세션 녹화됨 — $1점"]],
[/^Set (\d+) von (\d+) · Bläschen antippen wenn geschafft$/,["Set $1 of $2 · tap the bubble when done","第 $1/$2 组 · 完成后点击气泡","सेट $1/$2 · पूरा होने पर बबल दबाएं","Serie $1 de $2 · toca la burbuja al terminar","Série $1 sur $2 · touche la bulle une fois fait","المجموعة $1 من $2 · اضغط الفقاعة عند الانتهاء","সেট $1/$2 · শেষ হলে বুদবুদ চাপুন","Подход $1 из $2 · нажмите пузырёк, когда готово","Série $1 de $2 · toque na bolha ao concluir","سیٹ $1/$2 · مکمل ہونے پر بلبلہ دبائیں","Set $1 dari $2 · ketuk gelembung jika selesai","セット$1/$2 · 終わったらバブルをタップ","Set $1/$2 · bitince baloncuğa dokun","세트 $1/$2 · 완료 시 버블 탭"]],
[/^Übung (\d+)\/(\d+) · Sets zählen$/,["Exercise $1/$2 · count sets","动作 $1/$2 · 数组数","व्यायाम $1/$2 · सेट गिनें","Ejercicio $1/$2 · contar series","Exercice $1/$2 · compter les séries","تمرين $1/$2 · عدّ المجموعات","ব্যায়াম $1/$2 · সেট গুনুন","Упражнение $1/$2 · считайте подходы","Exercício $1/$2 · contar séries","مشق $1/$2 · سیٹ گنیں","Latihan $1/$2 · hitung set","種目$1/$2 · セットを数える","Hareket $1/$2 · setleri say","운동 $1/$2 · 세트 세기"]],
[/^(\d+) \/ (\d+) Sets$/,["$1 / $2 sets","$1 / $2 组","$1 / $2 सेट","$1 / $2 series","$1 / $2 séries","$1 / $2 مجموعات","$1 / $2 সেট","$1 / $2 подходов","$1 / $2 séries","$1 / $2 سیٹ","$1 / $2 set","$1 / $2 セット","$1 / $2 set","$1 / $2 세트"]],
[/^Review-Ergebnis — (.+)$/,["Review result — $1","评审结果——$1","समीक्षा परिणाम — $1","Resultado de revisión: $1","Résultat de vérification — $1","نتيجة المراجعة — $1","পর্যালোচনার ফলাফল — $1","Результат проверки — $1","Resultado da revisão — $1","جائزے کا نتیجہ — $1","Hasil tinjauan — $1","審査結果 — $1","İnceleme sonucu — $1","검토 결과 — $1"]],
[/^Aufstieg zu „(.+)“$/,["Advance to “$1”","晋级到「$1」","„$1“ में पदोन्नति","Ascenso a «$1»","Passage à « $1 »","الترقية إلى ”$1“","„$1“-এ উন্নতি","Переход на «$1»","Subida para “$1”","”$1“ میں ترقی","Naik ke “$1”","「$1」へ昇格","“$1” kademesine yükseliş","“$1” 승급"]],
[/^Fehler: (.+)$/,["Error: $1","错误：$1","त्रुटि: $1","Error: $1","Erreur : $1","خطأ: $1","ত্রুটি: $1","Ошибка: $1","Erro: $1","خرابی: $1","Kesalahan: $1","エラー：$1","Hata: $1","오류: $1"]],
[/^Video nicht verfügbar: (.+)$/,["Video unavailable: $1","视频不可用：$1","वीडियो अनुपलब्ध: $1","Vídeo no disponible: $1","Vidéo indisponible : $1","الفيديو غير متاح: $1","ভিডিও অনুপলব্ধ: $1","Видео недоступно: $1","Vídeo indisponível: $1","ویڈیو دستیاب نہیں: $1","Video tidak tersedia: $1","動画を利用できません：$1","Video kullanılamıyor: $1","영상을 사용할 수 없음: $1"]],
[/^Video-Upload fehlgeschlagen: (.+)$/,["Video upload failed: $1","视频上传失败：$1","वीडियो अपलोड विफल: $1","Error al subir el vídeo: $1","Échec de l'envoi de la vidéo : $1","فشل رفع الفيديو: $1","ভিডিও আপলোড ব্যর্থ: $1","Не удалось загрузить видео: $1","Falha no upload do vídeo: $1","ویڈیو اپ لوڈ ناکام: $1","Unggah video gagal: $1","動画のアップロード失敗：$1","Video yükleme başarısız: $1","영상 업로드 실패: $1"]],
[/^Kamera-Zugriff nicht möglich: (.+)$/,["Camera access failed: $1","无法访问相机：$1","कैमरा एक्सेस विफल: $1","Sin acceso a la cámara: $1","Accès caméra impossible : $1","تعذر الوصول للكاميرا: $1","ক্যামেরা প্রবেশ ব্যর্থ: $1","Нет доступа к камере: $1","Sem acesso à câmera: $1","کیمرہ رسائی ناکام: $1","Akses kamera gagal: $1","カメラにアクセスできません：$1","Kamera erişimi başarısız: $1","카메라 접근 실패: $1"]],
[/^Punktedeckel erreicht \((.+)\)$/,["Point cap reached ($1)","已达分数上限（$1）","अंक सीमा पूर्ण ($1)","Tope de puntos alcanzado ($1)","Plafond de points atteint ($1)","بلغت حد النقاط ($1)","পয়েন্ট সীমা পূর্ণ ($1)","Достигнут лимит очков ($1)","Limite de pontos atingido ($1)","پوائنٹ حد مکمل ($1)","Batas poin tercapai ($1)","ポイント上限（$1）","Puan sınırına ulaşıldı ($1)","포인트 상한 도달 ($1)"]],
[/^Satzpause: (.+)$/,["Rest: $1","组间休息：$1","विराम: $1","Descanso: $1","Repos : $1","الاستراحة: $1","বিরতি: $1","Отдых: $1","Descanso: $1","وقفہ: $1","Istirahat: $1","休憩：$1","Mola: $1","휴식: $1"]],
[/^Region: (.+) — Währung (.+)$/,["Region: $1 — currency $2","地区：$1——货币 $2","क्षेत्र: $1 — मुद्रा $2","Región: $1 — moneda $2","Région : $1 — devise $2","المنطقة: $1 — العملة $2","অঞ্চল: $1 — মুদ্রা $2","Регион: $1 — валюта $2","Região: $1 — moeda $2","علاقہ: $1 — کرنسی $2","Wilayah: $1 — mata uang $2","地域：$1 — 通貨 $2","Bölge: $1 — para birimi $2","지역: $1 — 통화 $2"]],
[/^Magic-Link an (.+) gesendet — Postfach prüfen$/,["Magic link sent to $1 — check your inbox","魔法链接已发送至 $1——请查收","$1 पर मैजिक लिंक भेजा — इनबॉक्स देखें","Enlace mágico enviado a $1: revisa tu correo","Lien magique envoyé à $1 — vérifie ta boîte","أُرسل رابط الدخول إلى $1 — تحقق من بريدك","$1-এ ম্যাজিক লিঙ্ক পাঠানো হয়েছে — ইনবক্স দেখুন","Ссылка отправлена на $1 — проверьте почту","Link mágico enviado para $1 — veja sua caixa","میجک لنک $1 پر بھیجا گیا — ان باکس دیکھیں","Tautan ajaib dikirim ke $1 — cek kotak masuk","マジックリンクを$1に送信 — 受信箱を確認","Sihirli bağlantı $1 adresine gönderildi — gelen kutunu kontrol et","매직 링크를 $1(으)로 전송 — 받은편지함 확인"]],
[/^(leicht|mittel|schwer) · (.+) Pkt\/Set$/,null],
[/^(\d+) \/ 30$/,null],
[/^30 Übungen · max (\d+) Pkt$/,["30 exercises · max $1 pts","30 个动作 · 最高 $1 分","30 व्यायाम · अधिकतम $1 अंक","30 ejercicios · máx $1 pts","30 exercices · max $1 pts","30 تمريناً · بحد أقصى $1 نقطة","৩০ ব্যায়াম · সর্বোচ্চ $1 পয়েন্ট","30 упражнений · макс $1 очк.","30 exercícios · máx $1 pts","30 مشقیں · زیادہ سے زیادہ $1 پوائنٹس","30 latihan · maks $1 poin","30種目・最大$1pt","30 hareket · maks $1 puan","30개 운동 · 최대 $1점"]]
];
// ── Laufzeit: übersetzt alle Textknoten + Platzhalter, beobachtet DOM-Änderungen ──
(function(){
  var lang=localStorage.getItem('rv-lang')||'de';
  document.documentElement.lang=lang;
  if(lang==='de')return; // Quellsprache
  var idx=window.I18N_ORDER.indexOf(lang); if(idx<0)return;
  var CAT={leicht:null,mittel:null,schwer:null};
  function lookup(key){
    var e=window.I18N_SRC[key]; if(e&&e[idx])return e[idx];
    for(var i=0;i<window.I18N_PATTERNS.length;i++){
      var p=window.I18N_PATTERNS[i]; if(!p[1])continue;
      var m=key.match(p[0]); if(!m)continue;
      var t=p[1][idx]; if(!t)return null;
      for(var g=1;g<m.length;g++)t=t.split('$'+g).join(m[g]);
      return t;
    }
    // Kategorie-Chip: "leicht · 1,5 Pkt/Set"
    var cm=key.match(/^(leicht|mittel|schwer) · (.+) Pkt\/Set$/);
    if(cm){var c=window.I18N_SRC[cm[1]];if(c&&c[idx])return c[idx]+' · '+cm[2]+' Pt/Set';}
    return null;
  }
  function trNode(n){
    var s=n.nodeValue; if(!s)return;
    var key=s.trim(); if(!key||key.length<2)return;
    var out=lookup(key);
    if(out!=null&&out!==key)n.nodeValue=s.replace(key,out);
  }
  function walk(node){
    if(node.nodeType===3){trNode(node);return;}
    if(node.nodeType!==1)return;
    var tag=node.tagName; if(tag==='SCRIPT'||tag==='STYLE')return;
    if(node.placeholder){var p=lookup(node.placeholder.trim()); if(p)node.placeholder=p;}
    for(var c=node.firstChild;c;c=c.nextSibling)walk(c);
  }
  function start(){
    walk(document.body);
    new MutationObserver(function(muts){
      for(var i=0;i<muts.length;i++){
        var m=muts[i];
        if(m.type==='characterData')trNode(m.target);
        else for(var j=0;j<m.addedNodes.length;j++)walk(m.addedNodes[j]);
      }
    }).observe(document.body,{childList:true,subtree:true,characterData:true});
  }
  if(document.body)start();else document.addEventListener('DOMContentLoaded',start);
})();
